# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""
Expr module, see official documentation at
https://dev.opencascade.org/doc/occt-7.9.0/refman/html/package_expr.html
"""

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Expr
else:
    import _Expr

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Expr.delete_SwigPyIterator

    def value(self):
        return _Expr.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _Expr.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _Expr.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _Expr.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _Expr.SwigPyIterator_equal(self, x)

    def copy(self):
        return _Expr.SwigPyIterator_copy(self)

    def next(self):
        return _Expr.SwigPyIterator_next(self)

    def __next__(self):
        return _Expr.SwigPyIterator___next__(self)

    def previous(self):
        return _Expr.SwigPyIterator_previous(self)

    def advance(self, n):
        return _Expr.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _Expr.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _Expr.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _Expr.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _Expr.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _Expr.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _Expr.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _Expr:
_Expr.SwigPyIterator_swigregister(SwigPyIterator)

def _dumps_object(klass):
    """ Overwrite default string output for any wrapped object.
    By default, __repr__ method returns something like:
    <OCC.Core.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x02BB0758> >
    This is too much verbose.
    We prefer :
    <class 'gp_Pnt'>
    or
    <class 'TopoDS_Shape'>
    """
    klass_name = str(klass.__class__).split(".")[3].split("'")[0]
    repr_string = "<class '" + klass_name + "'"
# for TopoDS_Shape, we also look for the base type
    if klass_name == "TopoDS_Shape":
        if klass.IsNull():
            repr_string += ": Null>"
            return repr_string
        st = klass.ShapeType()
        types = {OCC.Core.TopAbs.TopAbs_VERTEX: "Vertex",
                 OCC.Core.TopAbs.TopAbs_SOLID: "Solid",
                 OCC.Core.TopAbs.TopAbs_EDGE: "Edge",
                 OCC.Core.TopAbs.TopAbs_FACE: "Face",
                 OCC.Core.TopAbs.TopAbs_SHELL: "Shell",
                 OCC.Core.TopAbs.TopAbs_WIRE: "Wire",
                 OCC.Core.TopAbs.TopAbs_COMPOUND: "Compound",
                 OCC.Core.TopAbs.TopAbs_COMPSOLID: "Compsolid"}
        repr_string += "; Type:%s" % types[st]        
    elif hasattr(klass, "IsNull"):
        if klass.IsNull():
            repr_string += "; Null"
    repr_string += ">"
    return repr_string

PYTHONOCC_DEBUG_EXCEPTIONS = _Expr.PYTHONOCC_DEBUG_EXCEPTIONS

def get_readable_class_name(class_name):
    return _Expr.get_readable_class_name(class_name)

def get_readable_method_name(method_name):
    return _Expr.get_readable_method_name(method_name)

def get_exception_type(error):
    return _Expr.get_exception_type(error)

def process_opencascade_exception(error, method_name, class_name):
    return _Expr.process_opencascade_exception(error, method_name, class_name)

import warnings
from OCC.Wrapper.wrapper_utils import Proxy, deprecated

class ios_base(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    erase_event = _Expr.ios_base_erase_event
    imbue_event = _Expr.ios_base_imbue_event
    copyfmt_event = _Expr.ios_base_copyfmt_event

    def register_callback(self, __fn, __index):
        return _Expr.ios_base_register_callback(self, __fn, __index)

    def flags(self, *args):
        return _Expr.ios_base_flags(self, *args)

    def setf(self, *args):
        return _Expr.ios_base_setf(self, *args)

    def unsetf(self, __mask):
        return _Expr.ios_base_unsetf(self, __mask)

    def precision(self, *args):
        return _Expr.ios_base_precision(self, *args)

    def width(self, *args):
        return _Expr.ios_base_width(self, *args)

    @staticmethod
    def sync_with_stdio(__sync=True):
        return _Expr.ios_base_sync_with_stdio(__sync)

    def imbue(self, __loc):
        return _Expr.ios_base_imbue(self, __loc)

    def getloc(self):
        return _Expr.ios_base_getloc(self)

    @staticmethod
    def xalloc():
        return _Expr.ios_base_xalloc()

    def iword(self, __ix):
        return _Expr.ios_base_iword(self, __ix)

    def pword(self, __ix):
        return _Expr.ios_base_pword(self, __ix)
    __swig_destroy__ = _Expr.delete_ios_base

# Register ios_base in _Expr:
_Expr.ios_base_swigregister(ios_base)
cvar = _Expr.cvar
ios_base.boolalpha = _Expr.cvar.ios_base_boolalpha
ios_base.dec = _Expr.cvar.ios_base_dec
ios_base.fixed = _Expr.cvar.ios_base_fixed
ios_base.hex = _Expr.cvar.ios_base_hex
ios_base.internal = _Expr.cvar.ios_base_internal
ios_base.left = _Expr.cvar.ios_base_left
ios_base.oct = _Expr.cvar.ios_base_oct
ios_base.right = _Expr.cvar.ios_base_right
ios_base.scientific = _Expr.cvar.ios_base_scientific
ios_base.showbase = _Expr.cvar.ios_base_showbase
ios_base.showpoint = _Expr.cvar.ios_base_showpoint
ios_base.showpos = _Expr.cvar.ios_base_showpos
ios_base.skipws = _Expr.cvar.ios_base_skipws
ios_base.unitbuf = _Expr.cvar.ios_base_unitbuf
ios_base.uppercase = _Expr.cvar.ios_base_uppercase
ios_base.adjustfield = _Expr.cvar.ios_base_adjustfield
ios_base.basefield = _Expr.cvar.ios_base_basefield
ios_base.floatfield = _Expr.cvar.ios_base_floatfield
ios_base.badbit = _Expr.cvar.ios_base_badbit
ios_base.eofbit = _Expr.cvar.ios_base_eofbit
ios_base.failbit = _Expr.cvar.ios_base_failbit
ios_base.goodbit = _Expr.cvar.ios_base_goodbit
ios_base.app = _Expr.cvar.ios_base_app
ios_base.ate = _Expr.cvar.ios_base_ate
ios_base.binary = _Expr.cvar.ios_base_binary
ios_base.ios_base_in = _Expr.cvar.ios_base_ios_base_in
ios_base.out = _Expr.cvar.ios_base_out
ios_base.trunc = _Expr.cvar.ios_base_trunc
ios_base.beg = _Expr.cvar.ios_base_beg
ios_base.cur = _Expr.cvar.ios_base_cur
ios_base.end = _Expr.cvar.ios_base_end

class ios(ios_base):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def rdstate(self):
        return _Expr.ios_rdstate(self)

    def clear(self, *args):
        return _Expr.ios_clear(self, *args)

    def setstate(self, __state):
        return _Expr.ios_setstate(self, __state)

    def good(self):
        return _Expr.ios_good(self)

    def eof(self):
        return _Expr.ios_eof(self)

    def fail(self):
        return _Expr.ios_fail(self)

    def bad(self):
        return _Expr.ios_bad(self)

    def exceptions(self, *args):
        return _Expr.ios_exceptions(self, *args)

    def __init__(self, __sb):
        _Expr.ios_swiginit(self, _Expr.new_ios(__sb))
    __swig_destroy__ = _Expr.delete_ios

    def tie(self, *args):
        return _Expr.ios_tie(self, *args)

    def rdbuf(self, *args):
        return _Expr.ios_rdbuf(self, *args)

    def copyfmt(self, __rhs):
        return _Expr.ios_copyfmt(self, __rhs)

    def fill(self, *args):
        return _Expr.ios_fill(self, *args)

    def imbue(self, __loc):
        return _Expr.ios_imbue(self, __loc)

    def narrow(self, __c, __dfault):
        return _Expr.ios_narrow(self, __c, __dfault)

    def widen(self, __c):
        return _Expr.ios_widen(self, __c)

# Register ios in _Expr:
_Expr.ios_swigregister(ios)
class ostream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _Expr.ostream_swiginit(self, _Expr.new_ostream(__sb))
    __swig_destroy__ = _Expr.delete_ostream

    def __lshift__(self, *args):
        return _Expr.ostream___lshift__(self, *args)

    def put(self, __c):
        return _Expr.ostream_put(self, __c)

    def write(self, __s, __n):
        return _Expr.ostream_write(self, __s, __n)

    def flush(self):
        return _Expr.ostream_flush(self)

    def tellp(self):
        return _Expr.ostream_tellp(self)

    def seekp(self, *args):
        return _Expr.ostream_seekp(self, *args)

# Register ostream in _Expr:
_Expr.ostream_swigregister(ostream)
class istream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _Expr.istream_swiginit(self, _Expr.new_istream(__sb))
    __swig_destroy__ = _Expr.delete_istream

    def __rshift__(self, *args):
        return _Expr.istream___rshift__(self, *args)

    def gcount(self):
        return _Expr.istream_gcount(self)

    def get(self, *args):
        return _Expr.istream_get(self, *args)

    def getline(self, *args):
        return _Expr.istream_getline(self, *args)

    def ignore(self, *args):
        return _Expr.istream_ignore(self, *args)

    def peek(self):
        return _Expr.istream_peek(self)

    def read(self, __s, __n):
        return _Expr.istream_read(self, __s, __n)

    def readsome(self, __s, __n):
        return _Expr.istream_readsome(self, __s, __n)

    def putback(self, __c):
        return _Expr.istream_putback(self, __c)

    def unget(self):
        return _Expr.istream_unget(self)

    def sync(self):
        return _Expr.istream_sync(self)

    def tellg(self):
        return _Expr.istream_tellg(self)

    def seekg(self, *args):
        return _Expr.istream_seekg(self, *args)

# Register istream in _Expr:
_Expr.istream_swigregister(istream)
class iostream(istream, ostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _Expr.iostream_swiginit(self, _Expr.new_iostream(__sb))
    __swig_destroy__ = _Expr.delete_iostream

# Register iostream in _Expr:
_Expr.iostream_swigregister(iostream)
cin = cvar.cin
cout = cvar.cout
cerr = cvar.cerr
clog = cvar.clog

endl_cb_ptr = _Expr.endl_cb_ptr
endl = _Expr.endl
ends_cb_ptr = _Expr.ends_cb_ptr
ends = _Expr.ends
flush_cb_ptr = _Expr.flush_cb_ptr
flush = _Expr.flush
import OCC.Core.Standard
import OCC.Core.NCollection

from enum import IntEnum
from OCC.Core.Exception import *



class Expr_Array1OfGeneralExpression(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def begin(self, *args):
        return _Expr.Expr_Array1OfGeneralExpression_begin(self, *args)

    def cbegin(self):
        return _Expr.Expr_Array1OfGeneralExpression_cbegin(self)

    def end(self, *args):
        return _Expr.Expr_Array1OfGeneralExpression_end(self, *args)

    def cend(self):
        return _Expr.Expr_Array1OfGeneralExpression_cend(self)

    def __init__(self, *args):
        _Expr.Expr_Array1OfGeneralExpression_swiginit(self, _Expr.new_Expr_Array1OfGeneralExpression(*args))
    __swig_destroy__ = _Expr.delete_Expr_Array1OfGeneralExpression

    def Init(self, theValue):
        return _Expr.Expr_Array1OfGeneralExpression_Init(self, theValue)

    def Size(self):
        return _Expr.Expr_Array1OfGeneralExpression_Size(self)

    def Length(self):
        return _Expr.Expr_Array1OfGeneralExpression_Length(self)

    def IsEmpty(self):
        return _Expr.Expr_Array1OfGeneralExpression_IsEmpty(self)

    def Lower(self):
        return _Expr.Expr_Array1OfGeneralExpression_Lower(self)

    def Upper(self):
        return _Expr.Expr_Array1OfGeneralExpression_Upper(self)

    def Assign(self, theOther):
        return _Expr.Expr_Array1OfGeneralExpression_Assign(self, theOther)

    def Move(self, *args):
        return _Expr.Expr_Array1OfGeneralExpression_Move(self, *args)

    def Set(self, *args):
        return _Expr.Expr_Array1OfGeneralExpression_Set(self, *args)

    def First(self):
        return _Expr.Expr_Array1OfGeneralExpression_First(self)

    def ChangeFirst(self):
        return _Expr.Expr_Array1OfGeneralExpression_ChangeFirst(self)

    def Last(self):
        return _Expr.Expr_Array1OfGeneralExpression_Last(self)

    def ChangeLast(self):
        return _Expr.Expr_Array1OfGeneralExpression_ChangeLast(self)

    def Value(self, theIndex):
        return _Expr.Expr_Array1OfGeneralExpression_Value(self, theIndex)

    def ChangeValue(self, theIndex):
        return _Expr.Expr_Array1OfGeneralExpression_ChangeValue(self, theIndex)

    def __call__(self, *args):
        return _Expr.Expr_Array1OfGeneralExpression___call__(self, *args)

    def SetValue(self, *args):
        return _Expr.Expr_Array1OfGeneralExpression_SetValue(self, *args)

    def UpdateLowerBound(self, theLower):
        return _Expr.Expr_Array1OfGeneralExpression_UpdateLowerBound(self, theLower)

    def UpdateUpperBound(self, theUpper):
        return _Expr.Expr_Array1OfGeneralExpression_UpdateUpperBound(self, theUpper)

    def Resize(self, theLower, theUpper, theToCopyData):
        return _Expr.Expr_Array1OfGeneralExpression_Resize(self, theLower, theUpper, theToCopyData)

    def IsDeletable(self):
        return _Expr.Expr_Array1OfGeneralExpression_IsDeletable(self)

    def __getitem__(self, index):
        if index + self.Lower() > self.Upper():
            raise IndexError("index out of range")
        else:
            return self.Value(index + self.Lower())

    def __setitem__(self, index, value):
        if index + self.Lower() > self.Upper():
            raise IndexError("index out of range")
        else:
            self.SetValue(index + self.Lower(), value)

    def __len__(self):
        return self.Length()

    def __iter__(self):
        self.low = self.Lower()
        self.up = self.Upper()
        self.current = self.Lower() - 1
        return self

    def next(self):
        if self.current >= self.Upper():
            raise StopIteration
        else:
            self.current += 1
        return self.Value(self.current)

    __next__ = next


# Register Expr_Array1OfGeneralExpression in _Expr:
_Expr.Expr_Array1OfGeneralExpression_swigregister(Expr_Array1OfGeneralExpression)
class Expr_Array1OfNamedUnknown(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def begin(self, *args):
        return _Expr.Expr_Array1OfNamedUnknown_begin(self, *args)

    def cbegin(self):
        return _Expr.Expr_Array1OfNamedUnknown_cbegin(self)

    def end(self, *args):
        return _Expr.Expr_Array1OfNamedUnknown_end(self, *args)

    def cend(self):
        return _Expr.Expr_Array1OfNamedUnknown_cend(self)

    def __init__(self, *args):
        _Expr.Expr_Array1OfNamedUnknown_swiginit(self, _Expr.new_Expr_Array1OfNamedUnknown(*args))
    __swig_destroy__ = _Expr.delete_Expr_Array1OfNamedUnknown

    def Init(self, theValue):
        return _Expr.Expr_Array1OfNamedUnknown_Init(self, theValue)

    def Size(self):
        return _Expr.Expr_Array1OfNamedUnknown_Size(self)

    def Length(self):
        return _Expr.Expr_Array1OfNamedUnknown_Length(self)

    def IsEmpty(self):
        return _Expr.Expr_Array1OfNamedUnknown_IsEmpty(self)

    def Lower(self):
        return _Expr.Expr_Array1OfNamedUnknown_Lower(self)

    def Upper(self):
        return _Expr.Expr_Array1OfNamedUnknown_Upper(self)

    def Assign(self, theOther):
        return _Expr.Expr_Array1OfNamedUnknown_Assign(self, theOther)

    def Move(self, *args):
        return _Expr.Expr_Array1OfNamedUnknown_Move(self, *args)

    def Set(self, *args):
        return _Expr.Expr_Array1OfNamedUnknown_Set(self, *args)

    def First(self):
        return _Expr.Expr_Array1OfNamedUnknown_First(self)

    def ChangeFirst(self):
        return _Expr.Expr_Array1OfNamedUnknown_ChangeFirst(self)

    def Last(self):
        return _Expr.Expr_Array1OfNamedUnknown_Last(self)

    def ChangeLast(self):
        return _Expr.Expr_Array1OfNamedUnknown_ChangeLast(self)

    def Value(self, theIndex):
        return _Expr.Expr_Array1OfNamedUnknown_Value(self, theIndex)

    def ChangeValue(self, theIndex):
        return _Expr.Expr_Array1OfNamedUnknown_ChangeValue(self, theIndex)

    def __call__(self, *args):
        return _Expr.Expr_Array1OfNamedUnknown___call__(self, *args)

    def SetValue(self, *args):
        return _Expr.Expr_Array1OfNamedUnknown_SetValue(self, *args)

    def UpdateLowerBound(self, theLower):
        return _Expr.Expr_Array1OfNamedUnknown_UpdateLowerBound(self, theLower)

    def UpdateUpperBound(self, theUpper):
        return _Expr.Expr_Array1OfNamedUnknown_UpdateUpperBound(self, theUpper)

    def Resize(self, theLower, theUpper, theToCopyData):
        return _Expr.Expr_Array1OfNamedUnknown_Resize(self, theLower, theUpper, theToCopyData)

    def IsDeletable(self):
        return _Expr.Expr_Array1OfNamedUnknown_IsDeletable(self)

    def __getitem__(self, index):
        if index + self.Lower() > self.Upper():
            raise IndexError("index out of range")
        else:
            return self.Value(index + self.Lower())

    def __setitem__(self, index, value):
        if index + self.Lower() > self.Upper():
            raise IndexError("index out of range")
        else:
            self.SetValue(index + self.Lower(), value)

    def __len__(self):
        return self.Length()

    def __iter__(self):
        self.low = self.Lower()
        self.up = self.Upper()
        self.current = self.Lower() - 1
        return self

    def next(self):
        if self.current >= self.Upper():
            raise StopIteration
        else:
            self.current += 1
        return self.Value(self.current)

    __next__ = next


# Register Expr_Array1OfNamedUnknown in _Expr:
_Expr.Expr_Array1OfNamedUnknown_swigregister(Expr_Array1OfNamedUnknown)
class Expr_Array1OfSingleRelation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def begin(self, *args):
        return _Expr.Expr_Array1OfSingleRelation_begin(self, *args)

    def cbegin(self):
        return _Expr.Expr_Array1OfSingleRelation_cbegin(self)

    def end(self, *args):
        return _Expr.Expr_Array1OfSingleRelation_end(self, *args)

    def cend(self):
        return _Expr.Expr_Array1OfSingleRelation_cend(self)

    def __init__(self, *args):
        _Expr.Expr_Array1OfSingleRelation_swiginit(self, _Expr.new_Expr_Array1OfSingleRelation(*args))
    __swig_destroy__ = _Expr.delete_Expr_Array1OfSingleRelation

    def Init(self, theValue):
        return _Expr.Expr_Array1OfSingleRelation_Init(self, theValue)

    def Size(self):
        return _Expr.Expr_Array1OfSingleRelation_Size(self)

    def Length(self):
        return _Expr.Expr_Array1OfSingleRelation_Length(self)

    def IsEmpty(self):
        return _Expr.Expr_Array1OfSingleRelation_IsEmpty(self)

    def Lower(self):
        return _Expr.Expr_Array1OfSingleRelation_Lower(self)

    def Upper(self):
        return _Expr.Expr_Array1OfSingleRelation_Upper(self)

    def Assign(self, theOther):
        return _Expr.Expr_Array1OfSingleRelation_Assign(self, theOther)

    def Move(self, *args):
        return _Expr.Expr_Array1OfSingleRelation_Move(self, *args)

    def Set(self, *args):
        return _Expr.Expr_Array1OfSingleRelation_Set(self, *args)

    def First(self):
        return _Expr.Expr_Array1OfSingleRelation_First(self)

    def ChangeFirst(self):
        return _Expr.Expr_Array1OfSingleRelation_ChangeFirst(self)

    def Last(self):
        return _Expr.Expr_Array1OfSingleRelation_Last(self)

    def ChangeLast(self):
        return _Expr.Expr_Array1OfSingleRelation_ChangeLast(self)

    def Value(self, theIndex):
        return _Expr.Expr_Array1OfSingleRelation_Value(self, theIndex)

    def ChangeValue(self, theIndex):
        return _Expr.Expr_Array1OfSingleRelation_ChangeValue(self, theIndex)

    def __call__(self, *args):
        return _Expr.Expr_Array1OfSingleRelation___call__(self, *args)

    def SetValue(self, *args):
        return _Expr.Expr_Array1OfSingleRelation_SetValue(self, *args)

    def UpdateLowerBound(self, theLower):
        return _Expr.Expr_Array1OfSingleRelation_UpdateLowerBound(self, theLower)

    def UpdateUpperBound(self, theUpper):
        return _Expr.Expr_Array1OfSingleRelation_UpdateUpperBound(self, theUpper)

    def Resize(self, theLower, theUpper, theToCopyData):
        return _Expr.Expr_Array1OfSingleRelation_Resize(self, theLower, theUpper, theToCopyData)

    def IsDeletable(self):
        return _Expr.Expr_Array1OfSingleRelation_IsDeletable(self)

    def __getitem__(self, index):
        if index + self.Lower() > self.Upper():
            raise IndexError("index out of range")
        else:
            return self.Value(index + self.Lower())

    def __setitem__(self, index, value):
        if index + self.Lower() > self.Upper():
            raise IndexError("index out of range")
        else:
            self.SetValue(index + self.Lower(), value)

    def __len__(self):
        return self.Length()

    def __iter__(self):
        self.low = self.Lower()
        self.up = self.Upper()
        self.current = self.Lower() - 1
        return self

    def next(self):
        if self.current >= self.Upper():
            raise StopIteration
        else:
            self.current += 1
        return self.Value(self.current)

    __next__ = next


# Register Expr_Array1OfSingleRelation in _Expr:
_Expr.Expr_Array1OfSingleRelation_swigregister(Expr_Array1OfSingleRelation)
class Expr_MapOfNamedUnknown(OCC.Core.NCollection.NCollection_BaseMap):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def cbegin(self):
        return _Expr.Expr_MapOfNamedUnknown_cbegin(self)

    def cend(self):
        return _Expr.Expr_MapOfNamedUnknown_cend(self)

    def __init__(self, *args):
        _Expr.Expr_MapOfNamedUnknown_swiginit(self, _Expr.new_Expr_MapOfNamedUnknown(*args))

    def Exchange(self, theOther):
        return _Expr.Expr_MapOfNamedUnknown_Exchange(self, theOther)

    def Assign(self, theOther):
        return _Expr.Expr_MapOfNamedUnknown_Assign(self, theOther)

    def Set(self, *args):
        return _Expr.Expr_MapOfNamedUnknown_Set(self, *args)

    def ReSize(self, theExtent):
        return _Expr.Expr_MapOfNamedUnknown_ReSize(self, theExtent)

    def Add(self, *args):
        return _Expr.Expr_MapOfNamedUnknown_Add(self, *args)

    def Contains(self, theKey1):
        return _Expr.Expr_MapOfNamedUnknown_Contains(self, theKey1)

    def Substitute(self, theIndex, theKey1):
        return _Expr.Expr_MapOfNamedUnknown_Substitute(self, theIndex, theKey1)

    def Swap(self, theIndex1, theIndex2):
        return _Expr.Expr_MapOfNamedUnknown_Swap(self, theIndex1, theIndex2)

    def RemoveLast(self):
        return _Expr.Expr_MapOfNamedUnknown_RemoveLast(self)

    def RemoveFromIndex(self, theIndex):
        return _Expr.Expr_MapOfNamedUnknown_RemoveFromIndex(self, theIndex)

    def RemoveKey(self, theKey1):
        return _Expr.Expr_MapOfNamedUnknown_RemoveKey(self, theKey1)

    def FindKey(self, theIndex):
        return _Expr.Expr_MapOfNamedUnknown_FindKey(self, theIndex)

    def __call__(self, theIndex):
        return _Expr.Expr_MapOfNamedUnknown___call__(self, theIndex)

    def FindIndex(self, theKey1):
        return _Expr.Expr_MapOfNamedUnknown_FindIndex(self, theKey1)

    def Clear(self, *args):
        return _Expr.Expr_MapOfNamedUnknown_Clear(self, *args)
    __swig_destroy__ = _Expr.delete_Expr_MapOfNamedUnknown

    def Size(self):
        return _Expr.Expr_MapOfNamedUnknown_Size(self)

# Register Expr_MapOfNamedUnknown in _Expr:
_Expr.Expr_MapOfNamedUnknown_swigregister(Expr_MapOfNamedUnknown)
class Expr_SequenceOfGeneralExpression(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def begin(self):
        return _Expr.Expr_SequenceOfGeneralExpression_begin(self)

    def end(self):
        return _Expr.Expr_SequenceOfGeneralExpression_end(self)

    def cbegin(self):
        return _Expr.Expr_SequenceOfGeneralExpression_cbegin(self)

    def cend(self):
        return _Expr.Expr_SequenceOfGeneralExpression_cend(self)

    def __init__(self, *args):
        _Expr.Expr_SequenceOfGeneralExpression_swiginit(self, _Expr.new_Expr_SequenceOfGeneralExpression(*args))

    def Size(self):
        return _Expr.Expr_SequenceOfGeneralExpression_Size(self)

    def Length(self):
        return _Expr.Expr_SequenceOfGeneralExpression_Length(self)

    def Lower(self):
        return _Expr.Expr_SequenceOfGeneralExpression_Lower(self)

    def Upper(self):
        return _Expr.Expr_SequenceOfGeneralExpression_Upper(self)

    def IsEmpty(self):
        return _Expr.Expr_SequenceOfGeneralExpression_IsEmpty(self)

    def Reverse(self):
        return _Expr.Expr_SequenceOfGeneralExpression_Reverse(self)

    def Exchange(self, I, J):
        return _Expr.Expr_SequenceOfGeneralExpression_Exchange(self, I, J)

    @staticmethod
    def delNode(theNode, theAl):
        return _Expr.Expr_SequenceOfGeneralExpression_delNode(theNode, theAl)

    def Clear(self, theAllocator=0):
        return _Expr.Expr_SequenceOfGeneralExpression_Clear(self, theAllocator)

    def Assign(self, theOther):
        return _Expr.Expr_SequenceOfGeneralExpression_Assign(self, theOther)

    def Set(self, *args):
        return _Expr.Expr_SequenceOfGeneralExpression_Set(self, *args)

    def Remove(self, *args):
        return _Expr.Expr_SequenceOfGeneralExpression_Remove(self, *args)

    def Append(self, *args):
        return _Expr.Expr_SequenceOfGeneralExpression_Append(self, *args)

    def Prepend(self, *args):
        return _Expr.Expr_SequenceOfGeneralExpression_Prepend(self, *args)

    def InsertBefore(self, *args):
        return _Expr.Expr_SequenceOfGeneralExpression_InsertBefore(self, *args)

    def InsertAfter(self, *args):
        return _Expr.Expr_SequenceOfGeneralExpression_InsertAfter(self, *args)

    def Split(self, theIndex, theSeq):
        return _Expr.Expr_SequenceOfGeneralExpression_Split(self, theIndex, theSeq)

    def First(self):
        return _Expr.Expr_SequenceOfGeneralExpression_First(self)

    def ChangeFirst(self):
        return _Expr.Expr_SequenceOfGeneralExpression_ChangeFirst(self)

    def Last(self):
        return _Expr.Expr_SequenceOfGeneralExpression_Last(self)

    def ChangeLast(self):
        return _Expr.Expr_SequenceOfGeneralExpression_ChangeLast(self)

    def Value(self, theIndex):
        return _Expr.Expr_SequenceOfGeneralExpression_Value(self, theIndex)

    def ChangeValue(self, theIndex):
        return _Expr.Expr_SequenceOfGeneralExpression_ChangeValue(self, theIndex)

    def __call__(self, *args):
        return _Expr.Expr_SequenceOfGeneralExpression___call__(self, *args)

    def SetValue(self, theIndex, theItem):
        return _Expr.Expr_SequenceOfGeneralExpression_SetValue(self, theIndex, theItem)
    __swig_destroy__ = _Expr.delete_Expr_SequenceOfGeneralExpression

    def __len__(self):
        return self.Size()


# Register Expr_SequenceOfGeneralExpression in _Expr:
_Expr.Expr_SequenceOfGeneralExpression_swigregister(Expr_SequenceOfGeneralExpression)
class Expr_SequenceOfGeneralRelation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def begin(self):
        return _Expr.Expr_SequenceOfGeneralRelation_begin(self)

    def end(self):
        return _Expr.Expr_SequenceOfGeneralRelation_end(self)

    def cbegin(self):
        return _Expr.Expr_SequenceOfGeneralRelation_cbegin(self)

    def cend(self):
        return _Expr.Expr_SequenceOfGeneralRelation_cend(self)

    def __init__(self, *args):
        _Expr.Expr_SequenceOfGeneralRelation_swiginit(self, _Expr.new_Expr_SequenceOfGeneralRelation(*args))

    def Size(self):
        return _Expr.Expr_SequenceOfGeneralRelation_Size(self)

    def Length(self):
        return _Expr.Expr_SequenceOfGeneralRelation_Length(self)

    def Lower(self):
        return _Expr.Expr_SequenceOfGeneralRelation_Lower(self)

    def Upper(self):
        return _Expr.Expr_SequenceOfGeneralRelation_Upper(self)

    def IsEmpty(self):
        return _Expr.Expr_SequenceOfGeneralRelation_IsEmpty(self)

    def Reverse(self):
        return _Expr.Expr_SequenceOfGeneralRelation_Reverse(self)

    def Exchange(self, I, J):
        return _Expr.Expr_SequenceOfGeneralRelation_Exchange(self, I, J)

    @staticmethod
    def delNode(theNode, theAl):
        return _Expr.Expr_SequenceOfGeneralRelation_delNode(theNode, theAl)

    def Clear(self, theAllocator=0):
        return _Expr.Expr_SequenceOfGeneralRelation_Clear(self, theAllocator)

    def Assign(self, theOther):
        return _Expr.Expr_SequenceOfGeneralRelation_Assign(self, theOther)

    def Set(self, *args):
        return _Expr.Expr_SequenceOfGeneralRelation_Set(self, *args)

    def Remove(self, *args):
        return _Expr.Expr_SequenceOfGeneralRelation_Remove(self, *args)

    def Append(self, *args):
        return _Expr.Expr_SequenceOfGeneralRelation_Append(self, *args)

    def Prepend(self, *args):
        return _Expr.Expr_SequenceOfGeneralRelation_Prepend(self, *args)

    def InsertBefore(self, *args):
        return _Expr.Expr_SequenceOfGeneralRelation_InsertBefore(self, *args)

    def InsertAfter(self, *args):
        return _Expr.Expr_SequenceOfGeneralRelation_InsertAfter(self, *args)

    def Split(self, theIndex, theSeq):
        return _Expr.Expr_SequenceOfGeneralRelation_Split(self, theIndex, theSeq)

    def First(self):
        return _Expr.Expr_SequenceOfGeneralRelation_First(self)

    def ChangeFirst(self):
        return _Expr.Expr_SequenceOfGeneralRelation_ChangeFirst(self)

    def Last(self):
        return _Expr.Expr_SequenceOfGeneralRelation_Last(self)

    def ChangeLast(self):
        return _Expr.Expr_SequenceOfGeneralRelation_ChangeLast(self)

    def Value(self, theIndex):
        return _Expr.Expr_SequenceOfGeneralRelation_Value(self, theIndex)

    def ChangeValue(self, theIndex):
        return _Expr.Expr_SequenceOfGeneralRelation_ChangeValue(self, theIndex)

    def __call__(self, *args):
        return _Expr.Expr_SequenceOfGeneralRelation___call__(self, *args)

    def SetValue(self, theIndex, theItem):
        return _Expr.Expr_SequenceOfGeneralRelation_SetValue(self, theIndex, theItem)
    __swig_destroy__ = _Expr.delete_Expr_SequenceOfGeneralRelation

    def __len__(self):
        return self.Size()


# Register Expr_SequenceOfGeneralRelation in _Expr:
_Expr.Expr_SequenceOfGeneralRelation_swigregister(Expr_SequenceOfGeneralRelation)

@classnotwrapped
class Expr:
	pass

@classnotwrapped
class Expr_Absolute:
	pass

@classnotwrapped
class Expr_ArcCosine:
	pass

@classnotwrapped
class Expr_ArcSine:
	pass

@classnotwrapped
class Expr_ArcTangent:
	pass

@classnotwrapped
class Expr_ArgCosh:
	pass

@classnotwrapped
class Expr_ArgSinh:
	pass

@classnotwrapped
class Expr_ArgTanh:
	pass

@classnotwrapped
class Expr_BinaryExpression:
	pass

@classnotwrapped
class Expr_BinaryFunction:
	pass

@classnotwrapped
class Expr_Cosh:
	pass

@classnotwrapped
class Expr_Cosine:
	pass

@classnotwrapped
class Expr_Difference:
	pass

@classnotwrapped
class Expr_Different:
	pass

@classnotwrapped
class Expr_Division:
	pass

@classnotwrapped
class Expr_Equal:
	pass

@classnotwrapped
class Expr_Exponential:
	pass

@classnotwrapped
class Expr_Exponentiate:
	pass

@classnotwrapped
class Expr_FunctionDerivative:
	pass

@classnotwrapped
class Expr_GeneralExpression:
	pass

@classnotwrapped
class Expr_GeneralFunction:
	pass

@classnotwrapped
class Expr_GeneralRelation:
	pass

@classnotwrapped
class Expr_GreaterThan:
	pass

@classnotwrapped
class Expr_GreaterThanOrEqual:
	pass

@classnotwrapped
class Expr_LessThan:
	pass

@classnotwrapped
class Expr_LessThanOrEqual:
	pass

@classnotwrapped
class Expr_LogOf10:
	pass

@classnotwrapped
class Expr_LogOfe:
	pass

@classnotwrapped
class Expr_NamedConstant:
	pass

@classnotwrapped
class Expr_NamedExpression:
	pass

@classnotwrapped
class Expr_NamedFunction:
	pass

@classnotwrapped
class Expr_NamedUnknown:
	pass

@classnotwrapped
class Expr_NumericValue:
	pass

@classnotwrapped
class Expr_PolyExpression:
	pass

@classnotwrapped
class Expr_PolyFunction:
	pass

@classnotwrapped
class Expr_Product:
	pass

@classnotwrapped
class Expr_RUIterator:
	pass

@classnotwrapped
class Expr_RelationIterator:
	pass

@classnotwrapped
class Expr_Sign:
	pass

@classnotwrapped
class Expr_Sine:
	pass

@classnotwrapped
class Expr_SingleRelation:
	pass

@classnotwrapped
class Expr_Sinh:
	pass

@classnotwrapped
class Expr_Square:
	pass

@classnotwrapped
class Expr_SquareRoot:
	pass

@classnotwrapped
class Expr_Sum:
	pass

@classnotwrapped
class Expr_SystemRelation:
	pass

@classnotwrapped
class Expr_Tangent:
	pass

@classnotwrapped
class Expr_Tanh:
	pass

@classnotwrapped
class Expr_UnaryExpression:
	pass

@classnotwrapped
class Expr_UnaryFunction:
	pass

@classnotwrapped
class Expr_UnaryMinus:
	pass

@classnotwrapped
class Expr_UnknownIterator:
	pass





