# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""
IGESToBRep module, see official documentation at
https://dev.opencascade.org/doc/occt-7.9.0/refman/html/package_igestobrep.html
"""

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _IGESToBRep
else:
    import _IGESToBRep

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _IGESToBRep.delete_SwigPyIterator

    def value(self):
        return _IGESToBRep.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _IGESToBRep.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _IGESToBRep.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _IGESToBRep.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _IGESToBRep.SwigPyIterator_equal(self, x)

    def copy(self):
        return _IGESToBRep.SwigPyIterator_copy(self)

    def next(self):
        return _IGESToBRep.SwigPyIterator_next(self)

    def __next__(self):
        return _IGESToBRep.SwigPyIterator___next__(self)

    def previous(self):
        return _IGESToBRep.SwigPyIterator_previous(self)

    def advance(self, n):
        return _IGESToBRep.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _IGESToBRep.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _IGESToBRep.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _IGESToBRep.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _IGESToBRep.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _IGESToBRep.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _IGESToBRep.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _IGESToBRep:
_IGESToBRep.SwigPyIterator_swigregister(SwigPyIterator)

def _dumps_object(klass):
    """ Overwrite default string output for any wrapped object.
    By default, __repr__ method returns something like:
    <OCC.Core.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x02BB0758> >
    This is too much verbose.
    We prefer :
    <class 'gp_Pnt'>
    or
    <class 'TopoDS_Shape'>
    """
    klass_name = str(klass.__class__).split(".")[3].split("'")[0]
    repr_string = "<class '" + klass_name + "'"
# for TopoDS_Shape, we also look for the base type
    if klass_name == "TopoDS_Shape":
        if klass.IsNull():
            repr_string += ": Null>"
            return repr_string
        st = klass.ShapeType()
        types = {OCC.Core.TopAbs.TopAbs_VERTEX: "Vertex",
                 OCC.Core.TopAbs.TopAbs_SOLID: "Solid",
                 OCC.Core.TopAbs.TopAbs_EDGE: "Edge",
                 OCC.Core.TopAbs.TopAbs_FACE: "Face",
                 OCC.Core.TopAbs.TopAbs_SHELL: "Shell",
                 OCC.Core.TopAbs.TopAbs_WIRE: "Wire",
                 OCC.Core.TopAbs.TopAbs_COMPOUND: "Compound",
                 OCC.Core.TopAbs.TopAbs_COMPSOLID: "Compsolid"}
        repr_string += "; Type:%s" % types[st]        
    elif hasattr(klass, "IsNull"):
        if klass.IsNull():
            repr_string += "; Null"
    repr_string += ">"
    return repr_string

PYTHONOCC_DEBUG_EXCEPTIONS = _IGESToBRep.PYTHONOCC_DEBUG_EXCEPTIONS

def get_readable_class_name(class_name):
    return _IGESToBRep.get_readable_class_name(class_name)

def get_readable_method_name(method_name):
    return _IGESToBRep.get_readable_method_name(method_name)

def get_exception_type(error):
    return _IGESToBRep.get_exception_type(error)

def process_opencascade_exception(error, method_name, class_name):
    return _IGESToBRep.process_opencascade_exception(error, method_name, class_name)

import warnings
from OCC.Wrapper.wrapper_utils import Proxy, deprecated

class ios_base(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    erase_event = _IGESToBRep.ios_base_erase_event
    imbue_event = _IGESToBRep.ios_base_imbue_event
    copyfmt_event = _IGESToBRep.ios_base_copyfmt_event

    def register_callback(self, __fn, __index):
        return _IGESToBRep.ios_base_register_callback(self, __fn, __index)

    def flags(self, *args):
        return _IGESToBRep.ios_base_flags(self, *args)

    def setf(self, *args):
        return _IGESToBRep.ios_base_setf(self, *args)

    def unsetf(self, __mask):
        return _IGESToBRep.ios_base_unsetf(self, __mask)

    def precision(self, *args):
        return _IGESToBRep.ios_base_precision(self, *args)

    def width(self, *args):
        return _IGESToBRep.ios_base_width(self, *args)

    @staticmethod
    def sync_with_stdio(__sync=True):
        return _IGESToBRep.ios_base_sync_with_stdio(__sync)

    def imbue(self, __loc):
        return _IGESToBRep.ios_base_imbue(self, __loc)

    def getloc(self):
        return _IGESToBRep.ios_base_getloc(self)

    @staticmethod
    def xalloc():
        return _IGESToBRep.ios_base_xalloc()

    def iword(self, __ix):
        return _IGESToBRep.ios_base_iword(self, __ix)

    def pword(self, __ix):
        return _IGESToBRep.ios_base_pword(self, __ix)
    __swig_destroy__ = _IGESToBRep.delete_ios_base

# Register ios_base in _IGESToBRep:
_IGESToBRep.ios_base_swigregister(ios_base)
cvar = _IGESToBRep.cvar
ios_base.boolalpha = _IGESToBRep.cvar.ios_base_boolalpha
ios_base.dec = _IGESToBRep.cvar.ios_base_dec
ios_base.fixed = _IGESToBRep.cvar.ios_base_fixed
ios_base.hex = _IGESToBRep.cvar.ios_base_hex
ios_base.internal = _IGESToBRep.cvar.ios_base_internal
ios_base.left = _IGESToBRep.cvar.ios_base_left
ios_base.oct = _IGESToBRep.cvar.ios_base_oct
ios_base.right = _IGESToBRep.cvar.ios_base_right
ios_base.scientific = _IGESToBRep.cvar.ios_base_scientific
ios_base.showbase = _IGESToBRep.cvar.ios_base_showbase
ios_base.showpoint = _IGESToBRep.cvar.ios_base_showpoint
ios_base.showpos = _IGESToBRep.cvar.ios_base_showpos
ios_base.skipws = _IGESToBRep.cvar.ios_base_skipws
ios_base.unitbuf = _IGESToBRep.cvar.ios_base_unitbuf
ios_base.uppercase = _IGESToBRep.cvar.ios_base_uppercase
ios_base.adjustfield = _IGESToBRep.cvar.ios_base_adjustfield
ios_base.basefield = _IGESToBRep.cvar.ios_base_basefield
ios_base.floatfield = _IGESToBRep.cvar.ios_base_floatfield
ios_base.badbit = _IGESToBRep.cvar.ios_base_badbit
ios_base.eofbit = _IGESToBRep.cvar.ios_base_eofbit
ios_base.failbit = _IGESToBRep.cvar.ios_base_failbit
ios_base.goodbit = _IGESToBRep.cvar.ios_base_goodbit
ios_base.app = _IGESToBRep.cvar.ios_base_app
ios_base.ate = _IGESToBRep.cvar.ios_base_ate
ios_base.binary = _IGESToBRep.cvar.ios_base_binary
ios_base.ios_base_in = _IGESToBRep.cvar.ios_base_ios_base_in
ios_base.out = _IGESToBRep.cvar.ios_base_out
ios_base.trunc = _IGESToBRep.cvar.ios_base_trunc
ios_base.beg = _IGESToBRep.cvar.ios_base_beg
ios_base.cur = _IGESToBRep.cvar.ios_base_cur
ios_base.end = _IGESToBRep.cvar.ios_base_end

class ios(ios_base):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def rdstate(self):
        return _IGESToBRep.ios_rdstate(self)

    def clear(self, *args):
        return _IGESToBRep.ios_clear(self, *args)

    def setstate(self, __state):
        return _IGESToBRep.ios_setstate(self, __state)

    def good(self):
        return _IGESToBRep.ios_good(self)

    def eof(self):
        return _IGESToBRep.ios_eof(self)

    def fail(self):
        return _IGESToBRep.ios_fail(self)

    def bad(self):
        return _IGESToBRep.ios_bad(self)

    def exceptions(self, *args):
        return _IGESToBRep.ios_exceptions(self, *args)

    def __init__(self, __sb):
        _IGESToBRep.ios_swiginit(self, _IGESToBRep.new_ios(__sb))
    __swig_destroy__ = _IGESToBRep.delete_ios

    def tie(self, *args):
        return _IGESToBRep.ios_tie(self, *args)

    def rdbuf(self, *args):
        return _IGESToBRep.ios_rdbuf(self, *args)

    def copyfmt(self, __rhs):
        return _IGESToBRep.ios_copyfmt(self, __rhs)

    def fill(self, *args):
        return _IGESToBRep.ios_fill(self, *args)

    def imbue(self, __loc):
        return _IGESToBRep.ios_imbue(self, __loc)

    def narrow(self, __c, __dfault):
        return _IGESToBRep.ios_narrow(self, __c, __dfault)

    def widen(self, __c):
        return _IGESToBRep.ios_widen(self, __c)

# Register ios in _IGESToBRep:
_IGESToBRep.ios_swigregister(ios)
class ostream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _IGESToBRep.ostream_swiginit(self, _IGESToBRep.new_ostream(__sb))
    __swig_destroy__ = _IGESToBRep.delete_ostream

    def __lshift__(self, *args):
        return _IGESToBRep.ostream___lshift__(self, *args)

    def put(self, __c):
        return _IGESToBRep.ostream_put(self, __c)

    def write(self, __s, __n):
        return _IGESToBRep.ostream_write(self, __s, __n)

    def flush(self):
        return _IGESToBRep.ostream_flush(self)

    def tellp(self):
        return _IGESToBRep.ostream_tellp(self)

    def seekp(self, *args):
        return _IGESToBRep.ostream_seekp(self, *args)

# Register ostream in _IGESToBRep:
_IGESToBRep.ostream_swigregister(ostream)
class istream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _IGESToBRep.istream_swiginit(self, _IGESToBRep.new_istream(__sb))
    __swig_destroy__ = _IGESToBRep.delete_istream

    def __rshift__(self, *args):
        return _IGESToBRep.istream___rshift__(self, *args)

    def gcount(self):
        return _IGESToBRep.istream_gcount(self)

    def get(self, *args):
        return _IGESToBRep.istream_get(self, *args)

    def getline(self, *args):
        return _IGESToBRep.istream_getline(self, *args)

    def ignore(self, *args):
        return _IGESToBRep.istream_ignore(self, *args)

    def peek(self):
        return _IGESToBRep.istream_peek(self)

    def read(self, __s, __n):
        return _IGESToBRep.istream_read(self, __s, __n)

    def readsome(self, __s, __n):
        return _IGESToBRep.istream_readsome(self, __s, __n)

    def putback(self, __c):
        return _IGESToBRep.istream_putback(self, __c)

    def unget(self):
        return _IGESToBRep.istream_unget(self)

    def sync(self):
        return _IGESToBRep.istream_sync(self)

    def tellg(self):
        return _IGESToBRep.istream_tellg(self)

    def seekg(self, *args):
        return _IGESToBRep.istream_seekg(self, *args)

# Register istream in _IGESToBRep:
_IGESToBRep.istream_swigregister(istream)
class iostream(istream, ostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _IGESToBRep.iostream_swiginit(self, _IGESToBRep.new_iostream(__sb))
    __swig_destroy__ = _IGESToBRep.delete_iostream

# Register iostream in _IGESToBRep:
_IGESToBRep.iostream_swigregister(iostream)
cin = cvar.cin
cout = cvar.cout
cerr = cvar.cerr
clog = cvar.clog

endl_cb_ptr = _IGESToBRep.endl_cb_ptr
endl = _IGESToBRep.endl
ends_cb_ptr = _IGESToBRep.ends_cb_ptr
ends = _IGESToBRep.ends
flush_cb_ptr = _IGESToBRep.flush_cb_ptr
flush = _IGESToBRep.flush
import OCC.Core.Standard
import OCC.Core.NCollection
import OCC.Core.IGESData
import OCC.Core.Interface
import OCC.Core.TCollection
import OCC.Core.Message
import OCC.Core.OSD
import OCC.Core.TColStd
import OCC.Core.MoniTool
import OCC.Core.TopoDS
import OCC.Core.TopAbs
import OCC.Core.TopLoc
import OCC.Core.gp
import OCC.Core.Transfer
import OCC.Core.DE
import OCC.Core.TDocStd
import OCC.Core.TDF
import OCC.Core.CDF
import OCC.Core.CDM
import OCC.Core.Resource
import OCC.Core.PCDM
import OCC.Core.Storage
import OCC.Core.XSControl
import OCC.Core.IFSelect
import OCC.Core.TopTools
import OCC.Core.Geom
import OCC.Core.GeomAbs
import OCC.Core.TColgp
import OCC.Core.Geom2d
import OCC.Core.ShapeExtend
import OCC.Core.TColGeom

from enum import IntEnum
from OCC.Core.Exception import *




def Handle_IGESToBRep_Actor_Create():
    return _IGESToBRep.Handle_IGESToBRep_Actor_Create()

def Handle_IGESToBRep_Actor_DownCast(t):
    return _IGESToBRep.Handle_IGESToBRep_Actor_DownCast(t)

def Handle_IGESToBRep_Actor_IsNull(t):
    return _IGESToBRep.Handle_IGESToBRep_Actor_IsNull(t)

def Handle_IGESToBRep_Actor_ForceRelease(t):
    return _IGESToBRep.Handle_IGESToBRep_Actor_ForceRelease(t)

def Handle_IGESToBRep_Actor_GetRefCount(t):
    return _IGESToBRep.Handle_IGESToBRep_Actor_GetRefCount(t)

def Handle_IGESToBRep_AlgoContainer_Create():
    return _IGESToBRep.Handle_IGESToBRep_AlgoContainer_Create()

def Handle_IGESToBRep_AlgoContainer_DownCast(t):
    return _IGESToBRep.Handle_IGESToBRep_AlgoContainer_DownCast(t)

def Handle_IGESToBRep_AlgoContainer_IsNull(t):
    return _IGESToBRep.Handle_IGESToBRep_AlgoContainer_IsNull(t)

def Handle_IGESToBRep_AlgoContainer_ForceRelease(t):
    return _IGESToBRep.Handle_IGESToBRep_AlgoContainer_ForceRelease(t)

def Handle_IGESToBRep_AlgoContainer_GetRefCount(t):
    return _IGESToBRep.Handle_IGESToBRep_AlgoContainer_GetRefCount(t)

def Handle_IGESToBRep_IGESBoundary_Create():
    return _IGESToBRep.Handle_IGESToBRep_IGESBoundary_Create()

def Handle_IGESToBRep_IGESBoundary_DownCast(t):
    return _IGESToBRep.Handle_IGESToBRep_IGESBoundary_DownCast(t)

def Handle_IGESToBRep_IGESBoundary_IsNull(t):
    return _IGESToBRep.Handle_IGESToBRep_IGESBoundary_IsNull(t)

def Handle_IGESToBRep_IGESBoundary_ForceRelease(t):
    return _IGESToBRep.Handle_IGESToBRep_IGESBoundary_ForceRelease(t)

def Handle_IGESToBRep_IGESBoundary_GetRefCount(t):
    return _IGESToBRep.Handle_IGESToBRep_IGESBoundary_GetRefCount(t)

def Handle_IGESToBRep_ToolContainer_Create():
    return _IGESToBRep.Handle_IGESToBRep_ToolContainer_Create()

def Handle_IGESToBRep_ToolContainer_DownCast(t):
    return _IGESToBRep.Handle_IGESToBRep_ToolContainer_DownCast(t)

def Handle_IGESToBRep_ToolContainer_IsNull(t):
    return _IGESToBRep.Handle_IGESToBRep_ToolContainer_IsNull(t)

def Handle_IGESToBRep_ToolContainer_ForceRelease(t):
    return _IGESToBRep.Handle_IGESToBRep_ToolContainer_ForceRelease(t)

def Handle_IGESToBRep_ToolContainer_GetRefCount(t):
    return _IGESToBRep.Handle_IGESToBRep_ToolContainer_GetRefCount(t)
class igestobrep(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def AlgoContainer(*args):
        r"""
        Return
        -------
        opencascade::handle<IGESToBRep_AlgoContainer>

        Description
        -----------
        Returns default AlgoContainer.

        """
        return _IGESToBRep.igestobrep_AlgoContainer(*args)

    @staticmethod
    def IGESCurveToSequenceOfIGESCurve(*args):
        r"""

        Parameters
        ----------
        curve: IGESData_IGESEntity
        sequence: TColStd_HSequenceOfTransient

        Return
        -------
        int

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.igestobrep_IGESCurveToSequenceOfIGESCurve(*args)

    @staticmethod
    def Init(*args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Creates and initializes default AlgoContainer.

        """
        return _IGESToBRep.igestobrep_Init(*args)

    @staticmethod
    def IsBRepEntity(*args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        bool

        Description
        -----------
        Return True if the IGESEntity can be transferred by TransferBRepEntity. ex: VertexList, EdgeList, Loop, Face, Shell, Manifold Solid BRep Object from IGESSolid: 502, 504, 508, 510, 514, 186.

        """
        return _IGESToBRep.igestobrep_IsBRepEntity(*args)

    @staticmethod
    def IsBasicCurve(*args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        bool

        Description
        -----------
        Return True if the IGESEntity can be transferred by TransferBasicCurve. ex: CircularArc, ConicArc, Line, CopiousData, BSplineCurve, SplineCurve... from IGESGeom: 104,110,112,126.

        """
        return _IGESToBRep.igestobrep_IsBasicCurve(*args)

    @staticmethod
    def IsBasicSurface(*args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        bool

        Description
        -----------
        Return True if the IGESEntity can be transferred by TransferBasicSurface. ex: BSplineSurface, SplineSurface... from IGESGeom: 114,128.

        """
        return _IGESToBRep.igestobrep_IsBasicSurface(*args)

    @staticmethod
    def IsCurveAndSurface(*args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        bool

        Description
        -----------
        Return True if the IGESEntity can be transferred by TransferCurveAndSurface. ex: All IGESEntity from IGESGeom.

        """
        return _IGESToBRep.igestobrep_IsCurveAndSurface(*args)

    @staticmethod
    def IsTopoCurve(*args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        bool

        Description
        -----------
        Return True if the IGESEntity can be transferred by TransferTopoCurve. ex: all Curves from IGESGeom: all basic curves,102,130,142,144.

        """
        return _IGESToBRep.igestobrep_IsTopoCurve(*args)

    @staticmethod
    def IsTopoSurface(*args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        bool

        Description
        -----------
        Return True if the IGESEntity can be transferred by TransferTopoSurface. ex: All Surfaces from IGESGeom: all basic surfaces,108,118,120,122,141,143.

        """
        return _IGESToBRep.igestobrep_IsTopoSurface(*args)

    @staticmethod
    def SetAlgoContainer(*args):
        r"""

        Parameters
        ----------
        aContainer: IGESToBRep_AlgoContainer

        Return
        -------
        None

        Description
        -----------
        Sets default AlgoContainer.

        """
        return _IGESToBRep.igestobrep_SetAlgoContainer(*args)

    @staticmethod
    def TransferPCurve(*args):
        r"""

        Parameters
        ----------
        fromedge: TopoDS_Edge
        toedge: TopoDS_Edge
        face: TopoDS_Face

        Return
        -------
        bool

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.igestobrep_TransferPCurve(*args)

    __repr__ = _dumps_object


    def __init__(self):
        _IGESToBRep.igestobrep_swiginit(self, _IGESToBRep.new_igestobrep())
    __swig_destroy__ = _IGESToBRep.delete_igestobrep

# Register igestobrep in _IGESToBRep:
_IGESToBRep.igestobrep_swigregister(igestobrep)
class IGESToBRep_Actor(OCC.Core.Transfer.Transfer_ActorOfTransientProcess):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        No available documentation.

        """
        _IGESToBRep.IGESToBRep_Actor_swiginit(self, _IGESToBRep.new_IGESToBRep_Actor(*args))

    def GetContinuity(self, *args):
        r"""
        Return
        -------
        int

        Description
        -----------
        Return 'thecontinuity'.

        """
        return _IGESToBRep.IGESToBRep_Actor_GetContinuity(self, *args)

    def SetContinuity(self, *args):
        r"""

        Parameters
        ----------
        continuity: int (optional, default to 0)

        Return
        -------
        None

        Description
        -----------
        ---Purpose By default continuity = 0 if continuity = 1: try C1 if continuity = 2: try C2.

        """
        return _IGESToBRep.IGESToBRep_Actor_SetContinuity(self, *args)

    def SetModel(self, *args):
        r"""

        Parameters
        ----------
        model: Interface_InterfaceModel

        Return
        -------
        None

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_Actor_SetModel(self, *args)

    def UsedTolerance(self, *args):
        r"""
        Return
        -------
        float

        Description
        -----------
        Returns the tolerance which was actually used, either from the file or from statics.

        """
        return _IGESToBRep.IGESToBRep_Actor_UsedTolerance(self, *args)


    @staticmethod
    def DownCast(t):
      return Handle_IGESToBRep_Actor_DownCast(t)


    __repr__ = _dumps_object

    __swig_destroy__ = _IGESToBRep.delete_IGESToBRep_Actor

# Register IGESToBRep_Actor in _IGESToBRep:
_IGESToBRep.IGESToBRep_Actor_swigregister(IGESToBRep_Actor)
class IGESToBRep_AlgoContainer(OCC.Core.Standard.Standard_Transient):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Empty constructor.

        """
        _IGESToBRep.IGESToBRep_AlgoContainer_swiginit(self, _IGESToBRep.new_IGESToBRep_AlgoContainer(*args))

    def SetToolContainer(self, *args):
        r"""

        Parameters
        ----------
        TC: IGESToBRep_ToolContainer

        Return
        -------
        None

        Description
        -----------
        Sets ToolContainer.

        """
        return _IGESToBRep.IGESToBRep_AlgoContainer_SetToolContainer(self, *args)

    def ToolContainer(self, *args):
        r"""
        Return
        -------
        opencascade::handle<IGESToBRep_ToolContainer>

        Description
        -----------
        Returns ToolContainer.

        """
        return _IGESToBRep.IGESToBRep_AlgoContainer_ToolContainer(self, *args)


    @staticmethod
    def DownCast(t):
      return Handle_IGESToBRep_AlgoContainer_DownCast(t)


    __repr__ = _dumps_object

    __swig_destroy__ = _IGESToBRep.delete_IGESToBRep_AlgoContainer

# Register IGESToBRep_AlgoContainer in _IGESToBRep:
_IGESToBRep.IGESToBRep_AlgoContainer_swigregister(IGESToBRep_AlgoContainer)
class IGESToBRep_CurveAndSurface(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Creates a tool CurveAndSurface ready to run, with epsilons set to 1.E-04, myModeTopo to True, the optimization of the continuity to False.

        Parameters
        ----------
        eps: float
        epsGeom: float
        epsCoeff: float
        mode: bool
        modeapprox: bool
        optimized: bool

        Return
        -------
        None

        Description
        -----------
        Creates a tool CurveAndSurface ready to run.

        """
        _IGESToBRep.IGESToBRep_CurveAndSurface_swiginit(self, _IGESToBRep.new_IGESToBRep_CurveAndSurface(*args))

    def AddShapeResult(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity
        result: TopoDS_Shape

        Return
        -------
        None

        Description
        -----------
        set in 'myMap' the result of the transfer of the entity of the IGESEntity start ( type VertexList or EdgeList).

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_AddShapeResult(self, *args)

    def GetContinuity(self, *args):
        r"""
        Return
        -------
        int

        Description
        -----------
        Returns the value of 'myContinuity'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetContinuity(self, *args)

    def GetEpsCoeff(self, *args):
        r"""
        Return
        -------
        float

        Description
        -----------
        Returns the value of 'myEpsCoeff'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetEpsCoeff(self, *args)

    def GetEpsGeom(self, *args):
        r"""
        Return
        -------
        float

        Description
        -----------
        Returns the value of 'myEpsGeom'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetEpsGeom(self, *args)

    def GetEpsilon(self, *args):
        r"""
        Return
        -------
        float

        Description
        -----------
        Returns the value of 'myEps'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetEpsilon(self, *args)

    def GetMaxTol(self, *args):
        r"""
        Return
        -------
        float

        Description
        -----------
        Returns the value of 'myMaxTol'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetMaxTol(self, *args)

    def GetMinTol(self, *args):
        r"""
        Return
        -------
        float

        Description
        -----------
        Returns the value of 'myMinTol'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetMinTol(self, *args)

    def GetModeApprox(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Returns the value of 'myModeApprox'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetModeApprox(self, *args)

    def GetModeTransfer(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Returns the value of 'myModeIsTopo'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetModeTransfer(self, *args)

    def GetModel(self, *args):
        r"""
        Return
        -------
        opencascade::handle<IGESData_IGESModel>

        Description
        -----------
        Returns the value of 'myModel'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetModel(self, *args)

    def GetOptimized(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Returns the value of 'myContIsOpti'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetOptimized(self, *args)

    def GetShapeResult(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Returns the result of the transfer of the IGESEntity 'start' contained in 'myMap' . (if HasShapeResult is True).

        Parameters
        ----------
        start: IGESData_IGESEntity
        num: int

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Returns the numth result of the IGESEntity start (type VertexList or EdgeList) in 'myMap'. (if NbShapeResult is not null).

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetShapeResult(self, *args)

    def GetSurfaceCurve(self, *args):
        r"""
        Return
        -------
        int

        Description
        -----------
        Returns the value of 'mySurfaceCurve' 0 = value in file, 2 = keep 2d and compute 3d, 3 = keep 3d and compute 2d.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetSurfaceCurve(self, *args)

    def GetTransferProcess(self, *args):
        r"""
        Return
        -------
        opencascade::handle<Transfer_TransientProcess>

        Description
        -----------
        Returns the value of 'myMsgReg'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetTransferProcess(self, *args)

    def GetUVResolution(self, *args):
        r"""
        Return
        -------
        float

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetUVResolution(self, *args)

    def GetUnitFactor(self, *args):
        r"""
        Return
        -------
        float

        Description
        -----------
        Returns the value of ' myUnitFactor'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_GetUnitFactor(self, *args)

    def HasShapeResult(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        bool

        Description
        -----------
        Returns True if start was already treated and has a result in 'myMap' else returns False.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_HasShapeResult(self, *args)

    def Init(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Initializes the field of the tool CurveAndSurface with default creating values.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_Init(self, *args)

    def NbShapeResult(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        int

        Description
        -----------
        Returns the number of shapes results contained in 'myMap' for the IGESEntity start ( type VertexList or EdgeList).

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_NbShapeResult(self, *args)

    def SendFail(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity
        amsg: Message_Msg

        Return
        -------
        None

        Description
        -----------
        Records a new Fail message.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SendFail(self, *args)

    def SendMsg(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity
        amsg: Message_Msg

        Return
        -------
        None

        Description
        -----------
        Records a new Information message from the definition of a Msg (Original+Value).

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SendMsg(self, *args)

    def SendWarning(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity
        amsg: Message_Msg

        Return
        -------
        None

        Description
        -----------
        Records a new Warning message.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SendWarning(self, *args)

    def SetContinuity(self, *args):
        r"""

        Parameters
        ----------
        continuity: int

        Return
        -------
        None

        Description
        -----------
        Changes the value of 'myContinuity' if continuity = 0 do nothing else if continuity = 1 try C1 if continuity = 2 try C2.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetContinuity(self, *args)

    def SetEpsCoeff(self, *args):
        r"""

        Parameters
        ----------
        eps: float

        Return
        -------
        None

        Description
        -----------
        Changes the value of 'myEpsCoeff'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetEpsCoeff(self, *args)

    def SetEpsGeom(self, *args):
        r"""

        Parameters
        ----------
        eps: float

        Return
        -------
        None

        Description
        -----------
        Changes the value of 'myEpsGeom'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetEpsGeom(self, *args)

    def SetEpsilon(self, *args):
        r"""

        Parameters
        ----------
        eps: float

        Return
        -------
        None

        Description
        -----------
        Changes the value of 'myEps'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetEpsilon(self, *args)

    def SetMaxTol(self, *args):
        r"""

        Parameters
        ----------
        maxtol: float

        Return
        -------
        None

        Description
        -----------
        Changes the value of 'myMaxTol'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetMaxTol(self, *args)

    def SetMinTol(self, *args):
        r"""

        Parameters
        ----------
        mintol: float

        Return
        -------
        None

        Description
        -----------
        Changes the value of 'myMinTol'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetMinTol(self, *args)

    def SetModeApprox(self, *args):
        r"""

        Parameters
        ----------
        mode: bool

        Return
        -------
        None

        Description
        -----------
        Changes the value of 'myModeApprox'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetModeApprox(self, *args)

    def SetModeTransfer(self, *args):
        r"""

        Parameters
        ----------
        mode: bool

        Return
        -------
        None

        Description
        -----------
        Changes the value of 'myModeIsTopo'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetModeTransfer(self, *args)

    def SetModel(self, *args):
        r"""

        Parameters
        ----------
        model: IGESData_IGESModel

        Return
        -------
        None

        Description
        -----------
        Set the value of 'myModel'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetModel(self, *args)

    def SetOptimized(self, *args):
        r"""

        Parameters
        ----------
        optimized: bool

        Return
        -------
        None

        Description
        -----------
        Changes the value of 'myContIsOpti'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetOptimized(self, *args)

    def SetShapeResult(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity
        result: TopoDS_Shape

        Return
        -------
        None

        Description
        -----------
        set in 'myMap' the result of the transfer of the IGESEntity 'start'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetShapeResult(self, *args)

    def SetSurface(self, *args):
        r"""

        Parameters
        ----------
        theSurface: Geom_Surface

        Return
        -------
        None

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetSurface(self, *args)

    def SetSurfaceCurve(self, *args):
        r"""

        Parameters
        ----------
        ival: int

        Return
        -------
        None

        Description
        -----------
        Changes the value of 'mySurfaceCurve'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetSurfaceCurve(self, *args)

    def SetTransferProcess(self, *args):
        r"""

        Parameters
        ----------
        TP: Transfer_TransientProcess

        Return
        -------
        None

        Description
        -----------
        Set the value of 'myMsgReg'.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_SetTransferProcess(self, *args)

    def Surface(self, *args):
        r"""
        Return
        -------
        opencascade::handle<Geom_Surface>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_Surface(self, *args)

    def TransferCurveAndSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity
        theProgress: Message_ProgressRange (optional, default to Message_ProgressRange())

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Returns the result of the transfert of any IGES Curve or Surface Entity. If the transfer has failed, this member return a NullEntity.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_TransferCurveAndSurface(self, *args)

    def TransferGeometry(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity
        theProgress: Message_ProgressRange (optional, default to Message_ProgressRange())

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Returns the result of the transfert the geometry of any IGESEntity. If the transfer has failed, this member return a NullEntity.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_TransferGeometry(self, *args)

    def UpdateMinMaxTol(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Sets values of 'myMinTol' and 'myMaxTol' as follows myMaxTol = Max ('read.maxprecision.val', myEpsGeom * myUnitFactor) myMinTol = Precision::Confusion() Remark: This method is automatically invoked each time the values of 'myEpsGeom' or 'myUnitFactor' are changed.

        """
        return _IGESToBRep.IGESToBRep_CurveAndSurface_UpdateMinMaxTol(self, *args)

    __repr__ = _dumps_object

    __swig_destroy__ = _IGESToBRep.delete_IGESToBRep_CurveAndSurface

# Register IGESToBRep_CurveAndSurface in _IGESToBRep:
_IGESToBRep.IGESToBRep_CurveAndSurface_swigregister(IGESToBRep_CurveAndSurface)
class IGESToBRep_IGESBoundary(OCC.Core.Standard.Standard_Transient):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Empty constructor.

        Parameters
        ----------
        CS: IGESToBRep_CurveAndSurface

        Return
        -------
        None

        Description
        -----------
        Empty constructor.

        """
        _IGESToBRep.IGESToBRep_IGESBoundary_swiginit(self, _IGESToBRep.new_IGESToBRep_IGESBoundary(*args))

    def Check(self, *args):
        r"""

        Parameters
        ----------
        result: bool
        checkclosure: bool
        okCurve3d: bool
        okCurve2d: bool

        Return
        -------
        None

        Description
        -----------
        Checks result of translation of IGES boundary entities (types 141, 142 or 508). Checks consistency of 2D and 3D representations and keeps only one if they are inconsistent. <result>: result of translation (returned by Transfer), <checkclosure>: False for 142 without parent 144 entity, otherwise True, <okCurve3d>, <okCurve2d>: those returned by Transfer.

        """
        return _IGESToBRep.IGESToBRep_IGESBoundary_Check(self, *args)

    def Init(self, *args):
        r"""

        Parameters
        ----------
        CS: IGESToBRep_CurveAndSurface
        entity: IGESData_IGESEntity
        face: TopoDS_Face
        trans: gp_Trsf2d
        uFact: float
        filepreference: int

        Return
        -------
        None

        Description
        -----------
        Inits the object with parameters common for all types of IGES boundaries. <CS>: object to be used for retrieving translation parameters and sending messages, <entity>: boundary entity to be processed, <face>, <trans>, <uFact>: as for IGESToBRep_TopoCurve <filepreference>: preferred representation (2 or 3) given in the IGES file.

        """
        return _IGESToBRep.IGESToBRep_IGESBoundary_Init(self, *args)

    def Transfer(self, *args):
        r"""

        Parameters
        ----------
        curve3d: IGESData_IGESEntity
        toreverse3d: bool
        curves2d: IGESData_HArray1OfIGESEntity
        number: int

        Return
        -------
        okCurve: bool
        okCurve3d: bool
        okCurve2d: bool

        Description
        -----------
        Translates 141 and 142 entities. Returns True if the curve has been successfully translated, otherwise returns False. <okCurve..>: flags that indicate whether corresponding representation has been successfully translated (must be set to True before first call), <curve3d>: model space curve for 142 and current model space curve for 141, <toreverse3d>: False for 142 and current orientation flag for 141, <curves2d>: 1 parameter space curve for 142 or list of them for current model space curves for 141, <number>: 1 for 142 and rank number of model space curve for 141.

        Parameters
        ----------
        curve3d: ShapeExtend_WireData
        curves2d: IGESData_HArray1OfIGESEntity
        toreverse2d: bool
        number: int
        lsewd: ShapeExtend_WireData

        Return
        -------
        okCurve: bool
        okCurve3d: bool
        okCurve2d: bool

        Description
        -----------
        Translates 508 entity. Returns True if the curve has been successfully translated, otherwise returns False. Input object IGESBoundary must be created and initialized before. <okCurve..>: flags that indicate whether corresponding representation has been successfully translated (must be set to True before first call), <curve3d>: result of translation of current edge, <curves2d>: list of parameter space curves for edge, <toreverse2d>: orientation flag of current edge in respect to its model space curve, <number>: rank number of edge, <lsewd>: returns the result of translation of current edge.

        """
        return _IGESToBRep.IGESToBRep_IGESBoundary_Transfer(self, *args)

    def WireData(self, *args):
        r"""
        Return
        -------
        opencascade::handle<ShapeExtend_WireData>

        Description
        -----------
        Returns the resulting wire.

        """
        return _IGESToBRep.IGESToBRep_IGESBoundary_WireData(self, *args)

    def WireData2d(self, *args):
        r"""
        Return
        -------
        opencascade::handle<ShapeExtend_WireData>

        Description
        -----------
        Returns the wire from 2D curves (edges contain pcurves only).

        """
        return _IGESToBRep.IGESToBRep_IGESBoundary_WireData2d(self, *args)

    def WireData3d(self, *args):
        r"""
        Return
        -------
        opencascade::handle<ShapeExtend_WireData>

        Description
        -----------
        Returns the wire from 3D curves (edges contain 3D curves and may contain pcurves).

        """
        return _IGESToBRep.IGESToBRep_IGESBoundary_WireData3d(self, *args)


    @staticmethod
    def DownCast(t):
      return Handle_IGESToBRep_IGESBoundary_DownCast(t)


    __repr__ = _dumps_object

    __swig_destroy__ = _IGESToBRep.delete_IGESToBRep_IGESBoundary

# Register IGESToBRep_IGESBoundary in _IGESToBRep:
_IGESToBRep.IGESToBRep_IGESBoundary_swigregister(IGESToBRep_IGESBoundary)
class IGESToBRep_Reader(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Creates a Reader.

        """
        _IGESToBRep.IGESToBRep_Reader_swiginit(self, _IGESToBRep.new_IGESToBRep_Reader(*args))

    def Actor(self, *args):
        r"""
        Return
        -------
        opencascade::handle<IGESToBRep_Actor>

        Description
        -----------
        Returns 'theActor'.

        """
        return _IGESToBRep.IGESToBRep_Reader_Actor(self, *args)

    def Check(self, *args):
        r"""

        Parameters
        ----------
        withprint: bool

        Return
        -------
        bool

        Description
        -----------
        Checks the IGES file that was loaded into memory. Displays error messages in the default message file if withprint is true. Returns True if no fail message was found and False if there was at least one fail message.

        """
        return _IGESToBRep.IGESToBRep_Reader_Check(self, *args)

    def Clear(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Clears the results between two translation operations.

        """
        return _IGESToBRep.IGESToBRep_Reader_Clear(self, *args)

    def GetShapeFixParameters(self, *args):
        r"""
        Return
        -------
        XSAlgo_ShapeProcessor::ParameterMap

        Description
        -----------
        Returns parameters for shape processing that was set by SetParameters() method. 
        Return: the parameters for shape processing. Empty map if no parameters were set.

        """
        return _IGESToBRep.IGESToBRep_Reader_GetShapeFixParameters(self, *args)

    def GetShapeProcessFlags(self, *args):
        r"""
        Return
        -------
        ShapeProcess::OperationsFlags

        Description
        -----------
        Returns flags defining operations to be performed on shapes. 
        Return: The flags defining operations to be performed on shapes.

        """
        return _IGESToBRep.IGESToBRep_Reader_GetShapeProcessFlags(self, *args)

    def IsDone(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Returns True if the LAST Transfer/TransferRoots was a success.

        """
        return _IGESToBRep.IGESToBRep_Reader_IsDone(self, *args)

    def LoadFile(self, *args):
        r"""

        Parameters
        ----------
        filename: str

        Return
        -------
        int

        Description
        -----------
        Loads a Model from a file.Returns 0 if success. returns 1 if the file could not be opened, returns -1 if an error occurred while the file was being loaded.

        """
        return _IGESToBRep.IGESToBRep_Reader_LoadFile(self, *args)

    def Model(self, *args):
        r"""
        Return
        -------
        opencascade::handle<IGESData_IGESModel>

        Description
        -----------
        Returns the Model to be worked on.

        """
        return _IGESToBRep.IGESToBRep_Reader_Model(self, *args)

    def NbShapes(self, *args):
        r"""
        Return
        -------
        int

        Description
        -----------
        Returns the number of shapes produced by the translation.

        """
        return _IGESToBRep.IGESToBRep_Reader_NbShapes(self, *args)

    def OneShape(self, *args):
        r"""
        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Returns all of the results in a single shape which is: - a null shape if there are no results, - a shape if there is one result, - a compound containing the resulting shapes if there are several.

        """
        return _IGESToBRep.IGESToBRep_Reader_OneShape(self, *args)

    def SetModel(self, *args):
        r"""

        Parameters
        ----------
        model: IGESData_IGESModel

        Return
        -------
        None

        Description
        -----------
        Specifies a Model to work on Also clears the result and Done status, sets TransientProcess.

        """
        return _IGESToBRep.IGESToBRep_Reader_SetModel(self, *args)

    def SetShapeFixParameters(self, *args):
        r"""

        Parameters
        ----------
        theParameters: XSAlgo_ShapeProcessor::ParameterMap

        Return
        -------
        None

        Description
        -----------
        Sets parameters for shape processing. 
        Parameter theParameters the parameters for shape processing.

        Parameters
        ----------
        theParameters: XSAlgo_ShapeProcessor::ParameterMap

        Return
        -------
        None

        Description
        -----------
        Sets parameters for shape processing. Parameters are moved from the input map. 
        Parameter theParameters the parameters for shape processing.

        Parameters
        ----------
        theParameters: DE_ShapeFixParameters
        theAdditionalParameters: XSAlgo_ShapeProcessor::ParameterMap (optional, default to {})

        Return
        -------
        None

        Description
        -----------
        Sets parameters for shape processing. Parameters from @p theParameters are copied to the internal map. Parameters from @p theAdditionalParameters are copied to the internal map if they are not present in @p theParameters. 
        Parameter theParameters the parameters for shape processing. 
        Parameter theAdditionalParameters the additional parameters for shape processing.

        """
        return _IGESToBRep.IGESToBRep_Reader_SetShapeFixParameters(self, *args)

    def SetShapeProcessFlags(self, *args):
        r"""

        Parameters
        ----------
        theFlags: ShapeProcess::OperationsFlags

        Return
        -------
        None

        Description
        -----------
        Sets flags defining operations to be performed on shapes. 
        Parameter theFlags The flags defining operations to be performed on shapes.

        """
        return _IGESToBRep.IGESToBRep_Reader_SetShapeProcessFlags(self, *args)

    def SetTransientProcess(self, *args):
        r"""

        Parameters
        ----------
        TP: Transfer_TransientProcess

        Return
        -------
        None

        Description
        -----------
        Allows to set an already defined TransientProcess (to be called after LoadFile or SetModel).

        """
        return _IGESToBRep.IGESToBRep_Reader_SetTransientProcess(self, *args)

    def Shape(self, *args):
        r"""

        Parameters
        ----------
        num: int (optional, default to 1)

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Returns the num the resulting shape in a translation operation.

        """
        return _IGESToBRep.IGESToBRep_Reader_Shape(self, *args)

    def Transfer(self, *args):
        r"""

        Parameters
        ----------
        num: int
        theProgress: Message_ProgressRange (optional, default to Message_ProgressRange())

        Return
        -------
        bool

        Description
        -----------
        Transfers an Entity given its rank in the Model (Root or not) Returns True if it is recognized as Geom-Topol. (But it can have failed: see IsDone).

        """
        return _IGESToBRep.IGESToBRep_Reader_Transfer(self, *args)

    def TransferRoots(self, *args):
        r"""

        Parameters
        ----------
        onlyvisible: bool (optional, default to Standard_True)
        theProgress: Message_ProgressRange (optional, default to Message_ProgressRange())

        Return
        -------
        None

        Description
        -----------
        Translates root entities in an IGES file. Standard_True is the default value and means that only visible root entities are translated. Standard_False translates all of the roots (visible and invisible).

        """
        return _IGESToBRep.IGESToBRep_Reader_TransferRoots(self, *args)

    def TransientProcess(self, *args):
        r"""
        Return
        -------
        opencascade::handle<Transfer_TransientProcess>

        Description
        -----------
        Returns the TransientProcess.

        """
        return _IGESToBRep.IGESToBRep_Reader_TransientProcess(self, *args)

    def UsedTolerance(self, *args):
        r"""
        Return
        -------
        float

        Description
        -----------
        Returns the Tolerance which has been actually used, converted in millimeters (either that from File or that from Session, according the mode).

        """
        return _IGESToBRep.IGESToBRep_Reader_UsedTolerance(self, *args)

    __repr__ = _dumps_object

    __swig_destroy__ = _IGESToBRep.delete_IGESToBRep_Reader

# Register IGESToBRep_Reader in _IGESToBRep:
_IGESToBRep.IGESToBRep_Reader_swigregister(IGESToBRep_Reader)
class IGESToBRep_ToolContainer(OCC.Core.Standard.Standard_Transient):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Empty constructor.

        """
        _IGESToBRep.IGESToBRep_ToolContainer_swiginit(self, _IGESToBRep.new_IGESToBRep_ToolContainer(*args))

    def IGESBoundary(self, *args):
        r"""
        Return
        -------
        opencascade::handle<IGESToBRep_IGESBoundary>

        Description
        -----------
        Returns IGESToBRep_IGESBoundary.

        """
        return _IGESToBRep.IGESToBRep_ToolContainer_IGESBoundary(self, *args)


    @staticmethod
    def DownCast(t):
      return Handle_IGESToBRep_ToolContainer_DownCast(t)


    __repr__ = _dumps_object

    __swig_destroy__ = _IGESToBRep.delete_IGESToBRep_ToolContainer

# Register IGESToBRep_ToolContainer in _IGESToBRep:
_IGESToBRep.IGESToBRep_ToolContainer_swigregister(IGESToBRep_ToolContainer)
class IGESToBRep_BRepEntity(IGESToBRep_CurveAndSurface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Creates a tool BRepEntity ready to run, with epsilons set to 1.E-04, TheModeTopo to True, the optimization of the continuity to False.

        Parameters
        ----------
        CS: IGESToBRep_CurveAndSurface

        Return
        -------
        None

        Description
        -----------
        Creates a tool BRepEntity ready to run and sets its fields as CS's.

        Parameters
        ----------
        eps: float
        epsGeom: float
        epsCoeff: float
        mode: bool
        modeapprox: bool
        optimized: bool

        Return
        -------
        None

        Description
        -----------
        Creates a tool BRepEntity ready to run.

        """
        _IGESToBRep.IGESToBRep_BRepEntity_swiginit(self, _IGESToBRep.new_IGESToBRep_BRepEntity(*args))

    def TransferBRepEntity(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity
        theProgress: Message_ProgressRange (optional, default to Message_ProgressRange())

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Transfer the BRepEntity': Face, Shell or ManifoldSolid.

        """
        return _IGESToBRep.IGESToBRep_BRepEntity_TransferBRepEntity(self, *args)

    def TransferEdge(self, *args):
        r"""

        Parameters
        ----------
        start: IGESSolid_EdgeList
        index: int

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Transfer the entity number 'index' of the EdgeList 'start'.

        """
        return _IGESToBRep.IGESToBRep_BRepEntity_TransferEdge(self, *args)

    def TransferFace(self, *args):
        r"""

        Parameters
        ----------
        start: IGESSolid_Face

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Transfer the Face Entity.

        """
        return _IGESToBRep.IGESToBRep_BRepEntity_TransferFace(self, *args)

    def TransferLoop(self, *args):
        r"""

        Parameters
        ----------
        start: IGESSolid_Loop
        Face: TopoDS_Face
        trans: gp_Trsf2d
        uFact: float

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Transfer the Loop Entity.

        """
        return _IGESToBRep.IGESToBRep_BRepEntity_TransferLoop(self, *args)

    def TransferManifoldSolid(self, *args):
        r"""

        Parameters
        ----------
        start: IGESSolid_ManifoldSolid
        theProgress: Message_ProgressRange (optional, default to Message_ProgressRange())

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Transfer the ManifoldSolid Entity.

        """
        return _IGESToBRep.IGESToBRep_BRepEntity_TransferManifoldSolid(self, *args)

    def TransferShell(self, *args):
        r"""

        Parameters
        ----------
        start: IGESSolid_Shell
        theProgress: Message_ProgressRange (optional, default to Message_ProgressRange())

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Transfer the Shell Entity.

        """
        return _IGESToBRep.IGESToBRep_BRepEntity_TransferShell(self, *args)

    def TransferVertex(self, *args):
        r"""

        Parameters
        ----------
        start: IGESSolid_VertexList
        index: int

        Return
        -------
        TopoDS_Vertex

        Description
        -----------
        Transfer the entity number 'index' of the VertexList 'start'.

        """
        return _IGESToBRep.IGESToBRep_BRepEntity_TransferVertex(self, *args)

    __repr__ = _dumps_object

    __swig_destroy__ = _IGESToBRep.delete_IGESToBRep_BRepEntity

# Register IGESToBRep_BRepEntity in _IGESToBRep:
_IGESToBRep.IGESToBRep_BRepEntity_swigregister(IGESToBRep_BRepEntity)
class IGESToBRep_BasicCurve(IGESToBRep_CurveAndSurface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Creates a tool BasicCurve ready to run, with epsilons set to 1.E-04, TheModeTopo to True, the optimization of the continuity to False.

        Parameters
        ----------
        CS: IGESToBRep_CurveAndSurface

        Return
        -------
        None

        Description
        -----------
        Creates a tool BasicCurve ready to run and sets its fields as CS's.

        Parameters
        ----------
        eps: float
        epsGeom: float
        epsCoeff: float
        mode: bool
        modeapprox: bool
        optimized: bool

        Return
        -------
        None

        Description
        -----------
        Creates a tool BasicCurve ready to run.

        """
        _IGESToBRep.IGESToBRep_BasicCurve_swiginit(self, _IGESToBRep.new_IGESToBRep_BasicCurve(*args))

    def Transfer2dBSplineCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_BSplineCurve

        Return
        -------
        opencascade::handle<Geom2d_Curve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_Transfer2dBSplineCurve(self, *args)

    def Transfer2dBasicCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        opencascade::handle<Geom2d_Curve>

        Description
        -----------
        Transfert a IGESEntity which answer True to the member: IGESToBRep::IsBasicCurve(IGESEntity). The IGESEntity must be a curve UV and its associed TRSF must be planar .If this Entity could not be converted, this member returns a NullEntity.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_Transfer2dBasicCurve(self, *args)

    def Transfer2dCircularArc(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_CircularArc

        Return
        -------
        opencascade::handle<Geom2d_Curve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_Transfer2dCircularArc(self, *args)

    def Transfer2dConicArc(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_ConicArc

        Return
        -------
        opencascade::handle<Geom2d_Curve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_Transfer2dConicArc(self, *args)

    def Transfer2dCopiousData(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_CopiousData

        Return
        -------
        opencascade::handle<Geom2d_BSplineCurve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_Transfer2dCopiousData(self, *args)

    def Transfer2dLine(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_Line

        Return
        -------
        opencascade::handle<Geom2d_Curve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_Transfer2dLine(self, *args)

    def Transfer2dSplineCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_SplineCurve

        Return
        -------
        opencascade::handle<Geom2d_BSplineCurve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_Transfer2dSplineCurve(self, *args)

    def TransferBSplineCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_BSplineCurve

        Return
        -------
        opencascade::handle<Geom_Curve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_TransferBSplineCurve(self, *args)

    def TransferBasicCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        opencascade::handle<Geom_Curve>

        Description
        -----------
        Transfert a IGESEntity which answer True to the member: IGESToBRep::IsBasicCurve(IGESEntity). If this Entity could not be converted, this member returns a NullEntity.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_TransferBasicCurve(self, *args)

    def TransferCircularArc(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_CircularArc

        Return
        -------
        opencascade::handle<Geom_Curve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_TransferCircularArc(self, *args)

    def TransferConicArc(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_ConicArc

        Return
        -------
        opencascade::handle<Geom_Curve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_TransferConicArc(self, *args)

    def TransferCopiousData(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_CopiousData

        Return
        -------
        opencascade::handle<Geom_BSplineCurve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_TransferCopiousData(self, *args)

    def TransferLine(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_Line

        Return
        -------
        opencascade::handle<Geom_Curve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_TransferLine(self, *args)

    def TransferSplineCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_SplineCurve

        Return
        -------
        opencascade::handle<Geom_BSplineCurve>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_TransferSplineCurve(self, *args)

    def TransferTransformation(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_TransformationMatrix

        Return
        -------
        opencascade::handle<Geom_Transformation>

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_BasicCurve_TransferTransformation(self, *args)

    __repr__ = _dumps_object

    __swig_destroy__ = _IGESToBRep.delete_IGESToBRep_BasicCurve

# Register IGESToBRep_BasicCurve in _IGESToBRep:
_IGESToBRep.IGESToBRep_BasicCurve_swigregister(IGESToBRep_BasicCurve)
class IGESToBRep_BasicSurface(IGESToBRep_CurveAndSurface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Creates a tool BasicSurface ready to run, with epsilons set to 1.E-04, TheModeTopo to True, the optimization of the continuity to False.

        Parameters
        ----------
        CS: IGESToBRep_CurveAndSurface

        Return
        -------
        None

        Description
        -----------
        Creates a tool BasicSurface ready to run and sets its fields as CS's.

        Parameters
        ----------
        eps: float
        epsGeom: float
        epsCoeff: float
        mode: bool
        modeapprox: bool
        optimized: bool

        Return
        -------
        None

        Description
        -----------
        Creates a tool BasicSurface ready to run.

        """
        _IGESToBRep.IGESToBRep_BasicSurface_swiginit(self, _IGESToBRep.new_IGESToBRep_BasicSurface(*args))

    def TransferBSplineSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_BSplineSurface

        Return
        -------
        opencascade::handle<Geom_BSplineSurface>

        Description
        -----------
        Returns BSplineSurface from Geom if the transfer has succeeded.

        """
        return _IGESToBRep.IGESToBRep_BasicSurface_TransferBSplineSurface(self, *args)

    def TransferBasicSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        opencascade::handle<Geom_Surface>

        Description
        -----------
        Returns Surface from Geom if the last transfer has succeeded.

        """
        return _IGESToBRep.IGESToBRep_BasicSurface_TransferBasicSurface(self, *args)

    def TransferPlaneSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESSolid_PlaneSurface

        Return
        -------
        opencascade::handle<Geom_Plane>

        Description
        -----------
        Returns Plane from Geom if the transfer has succeeded.

        """
        return _IGESToBRep.IGESToBRep_BasicSurface_TransferPlaneSurface(self, *args)

    def TransferRigthConicalSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESSolid_ConicalSurface

        Return
        -------
        opencascade::handle<Geom_ConicalSurface>

        Description
        -----------
        Returns ConicalSurface from Geom if the transfer has succeeded.

        """
        return _IGESToBRep.IGESToBRep_BasicSurface_TransferRigthConicalSurface(self, *args)

    def TransferRigthCylindricalSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESSolid_CylindricalSurface

        Return
        -------
        opencascade::handle<Geom_CylindricalSurface>

        Description
        -----------
        Returns CylindricalSurface from Geom if the transfer has succeeded.

        """
        return _IGESToBRep.IGESToBRep_BasicSurface_TransferRigthCylindricalSurface(self, *args)

    def TransferSphericalSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESSolid_SphericalSurface

        Return
        -------
        opencascade::handle<Geom_SphericalSurface>

        Description
        -----------
        Returns SphericalSurface from Geom if the transfer has succeeded.

        """
        return _IGESToBRep.IGESToBRep_BasicSurface_TransferSphericalSurface(self, *args)

    def TransferSplineSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_SplineSurface

        Return
        -------
        opencascade::handle<Geom_BSplineSurface>

        Description
        -----------
        Returns BSplineSurface from Geom if the transfer has succeeded.

        """
        return _IGESToBRep.IGESToBRep_BasicSurface_TransferSplineSurface(self, *args)

    def TransferToroidalSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESSolid_ToroidalSurface

        Return
        -------
        opencascade::handle<Geom_ToroidalSurface>

        Description
        -----------
        Returns SphericalSurface from Geom if the transfer has succeeded.

        """
        return _IGESToBRep.IGESToBRep_BasicSurface_TransferToroidalSurface(self, *args)

    __repr__ = _dumps_object

    __swig_destroy__ = _IGESToBRep.delete_IGESToBRep_BasicSurface

# Register IGESToBRep_BasicSurface in _IGESToBRep:
_IGESToBRep.IGESToBRep_BasicSurface_swigregister(IGESToBRep_BasicSurface)
class IGESToBRep_TopoCurve(IGESToBRep_CurveAndSurface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Creates a tool TopoCurve ready to run, with epsilons set to 1.E-04, TheModeTopo to True, the optimization of the continuity to False.

        Parameters
        ----------
        CS: IGESToBRep_CurveAndSurface

        Return
        -------
        None

        Description
        -----------
        Creates a tool TopoCurve ready to run and sets its fields as CS's.

        Parameters
        ----------
        CS: IGESToBRep_TopoCurve

        Return
        -------
        None

        Description
        -----------
        Creates a tool TopoCurve ready to run and sets its fields as CS's.

        Parameters
        ----------
        eps: float
        epsGeom: float
        epsCoeff: float
        mode: bool
        modeapprox: bool
        optimized: bool

        Return
        -------
        None

        Description
        -----------
        Creates a tool TopoCurve ready to run.

        """
        _IGESToBRep.IGESToBRep_TopoCurve_swiginit(self, _IGESToBRep.new_IGESToBRep_TopoCurve(*args))

    def Approx2dBSplineCurve(self, *args):
        r"""

        Parameters
        ----------
        start: Geom2d_BSplineCurve

        Return
        -------
        None

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_Approx2dBSplineCurve(self, *args)

    def ApproxBSplineCurve(self, *args):
        r"""

        Parameters
        ----------
        start: Geom_BSplineCurve

        Return
        -------
        None

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_ApproxBSplineCurve(self, *args)

    def BadCase(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Returns TheBadCase flag.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_BadCase(self, *args)

    def Curve(self, *args):
        r"""

        Parameters
        ----------
        num: int (optional, default to 1)

        Return
        -------
        opencascade::handle<Geom_Curve>

        Description
        -----------
        Returns a Curve given its rank, by default the first one (null Curvee if out of range) in 'TheCurves'.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_Curve(self, *args)

    def Curve2d(self, *args):
        r"""

        Parameters
        ----------
        num: int (optional, default to 1)

        Return
        -------
        opencascade::handle<Geom2d_Curve>

        Description
        -----------
        Returns a Curve given its rank, by default the first one (null Curvee if out of range) in 'TheCurves2d'.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_Curve2d(self, *args)

    def NbCurves(self, *args):
        r"""
        Return
        -------
        int

        Description
        -----------
        Returns the count of Curves in 'TheCurves'.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_NbCurves(self, *args)

    def NbCurves2d(self, *args):
        r"""
        Return
        -------
        int

        Description
        -----------
        Returns the count of Curves in 'TheCurves2d'.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_NbCurves2d(self, *args)

    def SetBadCase(self, *args):
        r"""

        Parameters
        ----------
        value: bool

        Return
        -------
        None

        Description
        -----------
        Sets TheBadCase flag.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_SetBadCase(self, *args)

    def Transfer2dCompositeCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_CompositeCurve
        face: TopoDS_Face
        trans: gp_Trsf2d
        uFact: float

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_Transfer2dCompositeCurve(self, *args)

    def Transfer2dOffsetCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_OffsetCurve
        face: TopoDS_Face
        trans: gp_Trsf2d
        uFact: float

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_Transfer2dOffsetCurve(self, *args)

    def Transfer2dPoint(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_Point

        Return
        -------
        TopoDS_Vertex

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_Transfer2dPoint(self, *args)

    def Transfer2dTopoBasicCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity
        face: TopoDS_Face
        trans: gp_Trsf2d
        uFact: float

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_Transfer2dTopoBasicCurve(self, *args)

    def Transfer2dTopoCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity
        face: TopoDS_Face
        trans: gp_Trsf2d
        uFact: float

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_Transfer2dTopoCurve(self, *args)

    def TransferBoundary(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_Boundary

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_TransferBoundary(self, *args)

    def TransferBoundaryOnFace(self, *args):
        r"""

        Parameters
        ----------
        face: TopoDS_Face
        start: IGESGeom_Boundary
        trans: gp_Trsf2d
        uFact: float

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Transfers a Boundary directly on a face to trim it.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_TransferBoundaryOnFace(self, *args)

    def TransferCompositeCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_CompositeCurve

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_TransferCompositeCurve(self, *args)

    def TransferCurveOnFace(self, *args):
        r"""

        Parameters
        ----------
        face: TopoDS_Face
        start: IGESGeom_CurveOnSurface
        trans: gp_Trsf2d
        uFact: float
        IsCurv: bool

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        Transfers a CurveOnSurface directly on a face to trim it. The CurveOnSurface have to be defined Outer or Inner.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_TransferCurveOnFace(self, *args)

    def TransferCurveOnSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_CurveOnSurface

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_TransferCurveOnSurface(self, *args)

    def TransferOffsetCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_OffsetCurve

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_TransferOffsetCurve(self, *args)

    def TransferPoint(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_Point

        Return
        -------
        TopoDS_Vertex

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_TransferPoint(self, *args)

    def TransferTopoBasicCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_TransferTopoBasicCurve(self, *args)

    def TransferTopoCurve(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoCurve_TransferTopoCurve(self, *args)

    __repr__ = _dumps_object

    __swig_destroy__ = _IGESToBRep.delete_IGESToBRep_TopoCurve

# Register IGESToBRep_TopoCurve in _IGESToBRep:
_IGESToBRep.IGESToBRep_TopoCurve_swigregister(IGESToBRep_TopoCurve)
class IGESToBRep_TopoSurface(IGESToBRep_CurveAndSurface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Creates a tool TopoSurface ready to run, with epsilons set to 1.E-04, TheModeTopo to True, the optimization of the continuity to False.

        Parameters
        ----------
        CS: IGESToBRep_CurveAndSurface

        Return
        -------
        None

        Description
        -----------
        Creates a tool TopoSurface ready to run and sets its fields as CS's.

        Parameters
        ----------
        eps: float
        epsGeom: float
        epsCoeff: float
        mode: bool
        modeapprox: bool
        optimized: bool

        Return
        -------
        None

        Description
        -----------
        Creates a tool TopoSurface ready to run.

        """
        _IGESToBRep.IGESToBRep_TopoSurface_swiginit(self, _IGESToBRep.new_IGESToBRep_TopoSurface(*args))

    def ParamSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity
        trans: gp_Trsf2d

        Return
        -------
        uFact: float

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoSurface_ParamSurface(self, *args)

    def TransferBoundedSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_BoundedSurface

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoSurface_TransferBoundedSurface(self, *args)

    def TransferOffsetSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_OffsetSurface

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoSurface_TransferOffsetSurface(self, *args)

    def TransferPerforate(self, *args):
        r"""

        Parameters
        ----------
        start: IGESBasic_SingleParent

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoSurface_TransferPerforate(self, *args)

    def TransferPlane(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_Plane

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoSurface_TransferPlane(self, *args)

    def TransferRuledSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_RuledSurface

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoSurface_TransferRuledSurface(self, *args)

    def TransferSurfaceOfRevolution(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_SurfaceOfRevolution

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoSurface_TransferSurfaceOfRevolution(self, *args)

    def TransferTabulatedCylinder(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_TabulatedCylinder

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoSurface_TransferTabulatedCylinder(self, *args)

    def TransferTopoBasicSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoSurface_TransferTopoBasicSurface(self, *args)

    def TransferTopoSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESData_IGESEntity

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoSurface_TransferTopoSurface(self, *args)

    def TransferTrimmedSurface(self, *args):
        r"""

        Parameters
        ----------
        start: IGESGeom_TrimmedSurface

        Return
        -------
        TopoDS_Shape

        Description
        -----------
        No available documentation.

        """
        return _IGESToBRep.IGESToBRep_TopoSurface_TransferTrimmedSurface(self, *args)

    __repr__ = _dumps_object

    @methodnotwrapped
    def TransferPlaneSurface(self):
    	pass

    __swig_destroy__ = _IGESToBRep.delete_IGESToBRep_TopoSurface

# Register IGESToBRep_TopoSurface in _IGESToBRep:
_IGESToBRep.IGESToBRep_TopoSurface_swigregister(IGESToBRep_TopoSurface)



@deprecated
def igestobrep_AlgoContainer(*args):
	return igestobrep.AlgoContainer(*args)

@deprecated
def igestobrep_IGESCurveToSequenceOfIGESCurve(*args):
	return igestobrep.IGESCurveToSequenceOfIGESCurve(*args)

@deprecated
def igestobrep_Init(*args):
	return igestobrep.Init(*args)

@deprecated
def igestobrep_IsBRepEntity(*args):
	return igestobrep.IsBRepEntity(*args)

@deprecated
def igestobrep_IsBasicCurve(*args):
	return igestobrep.IsBasicCurve(*args)

@deprecated
def igestobrep_IsBasicSurface(*args):
	return igestobrep.IsBasicSurface(*args)

@deprecated
def igestobrep_IsCurveAndSurface(*args):
	return igestobrep.IsCurveAndSurface(*args)

@deprecated
def igestobrep_IsTopoCurve(*args):
	return igestobrep.IsTopoCurve(*args)

@deprecated
def igestobrep_IsTopoSurface(*args):
	return igestobrep.IsTopoSurface(*args)

@deprecated
def igestobrep_SetAlgoContainer(*args):
	return igestobrep.SetAlgoContainer(*args)

@deprecated
def igestobrep_TransferPCurve(*args):
	return igestobrep.TransferPCurve(*args)



