# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""
RWGltf module, see official documentation at
https://dev.opencascade.org/doc/occt-7.9.0/refman/html/package_rwgltf.html
"""

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _RWGltf
else:
    import _RWGltf

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _RWGltf.delete_SwigPyIterator

    def value(self):
        return _RWGltf.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _RWGltf.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _RWGltf.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _RWGltf.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _RWGltf.SwigPyIterator_equal(self, x)

    def copy(self):
        return _RWGltf.SwigPyIterator_copy(self)

    def next(self):
        return _RWGltf.SwigPyIterator_next(self)

    def __next__(self):
        return _RWGltf.SwigPyIterator___next__(self)

    def previous(self):
        return _RWGltf.SwigPyIterator_previous(self)

    def advance(self, n):
        return _RWGltf.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _RWGltf.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _RWGltf.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _RWGltf.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _RWGltf.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _RWGltf.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _RWGltf.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _RWGltf:
_RWGltf.SwigPyIterator_swigregister(SwigPyIterator)

def _dumps_object(klass):
    """ Overwrite default string output for any wrapped object.
    By default, __repr__ method returns something like:
    <OCC.Core.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x02BB0758> >
    This is too much verbose.
    We prefer :
    <class 'gp_Pnt'>
    or
    <class 'TopoDS_Shape'>
    """
    klass_name = str(klass.__class__).split(".")[3].split("'")[0]
    repr_string = "<class '" + klass_name + "'"
# for TopoDS_Shape, we also look for the base type
    if klass_name == "TopoDS_Shape":
        if klass.IsNull():
            repr_string += ": Null>"
            return repr_string
        st = klass.ShapeType()
        types = {OCC.Core.TopAbs.TopAbs_VERTEX: "Vertex",
                 OCC.Core.TopAbs.TopAbs_SOLID: "Solid",
                 OCC.Core.TopAbs.TopAbs_EDGE: "Edge",
                 OCC.Core.TopAbs.TopAbs_FACE: "Face",
                 OCC.Core.TopAbs.TopAbs_SHELL: "Shell",
                 OCC.Core.TopAbs.TopAbs_WIRE: "Wire",
                 OCC.Core.TopAbs.TopAbs_COMPOUND: "Compound",
                 OCC.Core.TopAbs.TopAbs_COMPSOLID: "Compsolid"}
        repr_string += "; Type:%s" % types[st]        
    elif hasattr(klass, "IsNull"):
        if klass.IsNull():
            repr_string += "; Null"
    repr_string += ">"
    return repr_string

PYTHONOCC_DEBUG_EXCEPTIONS = _RWGltf.PYTHONOCC_DEBUG_EXCEPTIONS

def get_readable_class_name(class_name):
    return _RWGltf.get_readable_class_name(class_name)

def get_readable_method_name(method_name):
    return _RWGltf.get_readable_method_name(method_name)

def get_exception_type(error):
    return _RWGltf.get_exception_type(error)

def process_opencascade_exception(error, method_name, class_name):
    return _RWGltf.process_opencascade_exception(error, method_name, class_name)

import warnings
from OCC.Wrapper.wrapper_utils import Proxy, deprecated

class ios_base(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    erase_event = _RWGltf.ios_base_erase_event
    imbue_event = _RWGltf.ios_base_imbue_event
    copyfmt_event = _RWGltf.ios_base_copyfmt_event

    def register_callback(self, __fn, __index):
        return _RWGltf.ios_base_register_callback(self, __fn, __index)

    def flags(self, *args):
        return _RWGltf.ios_base_flags(self, *args)

    def setf(self, *args):
        return _RWGltf.ios_base_setf(self, *args)

    def unsetf(self, __mask):
        return _RWGltf.ios_base_unsetf(self, __mask)

    def precision(self, *args):
        return _RWGltf.ios_base_precision(self, *args)

    def width(self, *args):
        return _RWGltf.ios_base_width(self, *args)

    @staticmethod
    def sync_with_stdio(__sync=True):
        return _RWGltf.ios_base_sync_with_stdio(__sync)

    def imbue(self, __loc):
        return _RWGltf.ios_base_imbue(self, __loc)

    def getloc(self):
        return _RWGltf.ios_base_getloc(self)

    @staticmethod
    def xalloc():
        return _RWGltf.ios_base_xalloc()

    def iword(self, __ix):
        return _RWGltf.ios_base_iword(self, __ix)

    def pword(self, __ix):
        return _RWGltf.ios_base_pword(self, __ix)
    __swig_destroy__ = _RWGltf.delete_ios_base

# Register ios_base in _RWGltf:
_RWGltf.ios_base_swigregister(ios_base)
cvar = _RWGltf.cvar
ios_base.boolalpha = _RWGltf.cvar.ios_base_boolalpha
ios_base.dec = _RWGltf.cvar.ios_base_dec
ios_base.fixed = _RWGltf.cvar.ios_base_fixed
ios_base.hex = _RWGltf.cvar.ios_base_hex
ios_base.internal = _RWGltf.cvar.ios_base_internal
ios_base.left = _RWGltf.cvar.ios_base_left
ios_base.oct = _RWGltf.cvar.ios_base_oct
ios_base.right = _RWGltf.cvar.ios_base_right
ios_base.scientific = _RWGltf.cvar.ios_base_scientific
ios_base.showbase = _RWGltf.cvar.ios_base_showbase
ios_base.showpoint = _RWGltf.cvar.ios_base_showpoint
ios_base.showpos = _RWGltf.cvar.ios_base_showpos
ios_base.skipws = _RWGltf.cvar.ios_base_skipws
ios_base.unitbuf = _RWGltf.cvar.ios_base_unitbuf
ios_base.uppercase = _RWGltf.cvar.ios_base_uppercase
ios_base.adjustfield = _RWGltf.cvar.ios_base_adjustfield
ios_base.basefield = _RWGltf.cvar.ios_base_basefield
ios_base.floatfield = _RWGltf.cvar.ios_base_floatfield
ios_base.badbit = _RWGltf.cvar.ios_base_badbit
ios_base.eofbit = _RWGltf.cvar.ios_base_eofbit
ios_base.failbit = _RWGltf.cvar.ios_base_failbit
ios_base.goodbit = _RWGltf.cvar.ios_base_goodbit
ios_base.app = _RWGltf.cvar.ios_base_app
ios_base.ate = _RWGltf.cvar.ios_base_ate
ios_base.binary = _RWGltf.cvar.ios_base_binary
ios_base.ios_base_in = _RWGltf.cvar.ios_base_ios_base_in
ios_base.out = _RWGltf.cvar.ios_base_out
ios_base.trunc = _RWGltf.cvar.ios_base_trunc
ios_base.beg = _RWGltf.cvar.ios_base_beg
ios_base.cur = _RWGltf.cvar.ios_base_cur
ios_base.end = _RWGltf.cvar.ios_base_end

class ios(ios_base):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def rdstate(self):
        return _RWGltf.ios_rdstate(self)

    def clear(self, *args):
        return _RWGltf.ios_clear(self, *args)

    def setstate(self, __state):
        return _RWGltf.ios_setstate(self, __state)

    def good(self):
        return _RWGltf.ios_good(self)

    def eof(self):
        return _RWGltf.ios_eof(self)

    def fail(self):
        return _RWGltf.ios_fail(self)

    def bad(self):
        return _RWGltf.ios_bad(self)

    def exceptions(self, *args):
        return _RWGltf.ios_exceptions(self, *args)

    def __init__(self, __sb):
        _RWGltf.ios_swiginit(self, _RWGltf.new_ios(__sb))
    __swig_destroy__ = _RWGltf.delete_ios

    def tie(self, *args):
        return _RWGltf.ios_tie(self, *args)

    def rdbuf(self, *args):
        return _RWGltf.ios_rdbuf(self, *args)

    def copyfmt(self, __rhs):
        return _RWGltf.ios_copyfmt(self, __rhs)

    def fill(self, *args):
        return _RWGltf.ios_fill(self, *args)

    def imbue(self, __loc):
        return _RWGltf.ios_imbue(self, __loc)

    def narrow(self, __c, __dfault):
        return _RWGltf.ios_narrow(self, __c, __dfault)

    def widen(self, __c):
        return _RWGltf.ios_widen(self, __c)

# Register ios in _RWGltf:
_RWGltf.ios_swigregister(ios)
class ostream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _RWGltf.ostream_swiginit(self, _RWGltf.new_ostream(__sb))
    __swig_destroy__ = _RWGltf.delete_ostream

    def __lshift__(self, *args):
        return _RWGltf.ostream___lshift__(self, *args)

    def put(self, __c):
        return _RWGltf.ostream_put(self, __c)

    def write(self, __s, __n):
        return _RWGltf.ostream_write(self, __s, __n)

    def flush(self):
        return _RWGltf.ostream_flush(self)

    def tellp(self):
        return _RWGltf.ostream_tellp(self)

    def seekp(self, *args):
        return _RWGltf.ostream_seekp(self, *args)

# Register ostream in _RWGltf:
_RWGltf.ostream_swigregister(ostream)
class istream(ios):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _RWGltf.istream_swiginit(self, _RWGltf.new_istream(__sb))
    __swig_destroy__ = _RWGltf.delete_istream

    def __rshift__(self, *args):
        return _RWGltf.istream___rshift__(self, *args)

    def gcount(self):
        return _RWGltf.istream_gcount(self)

    def get(self, *args):
        return _RWGltf.istream_get(self, *args)

    def getline(self, *args):
        return _RWGltf.istream_getline(self, *args)

    def ignore(self, *args):
        return _RWGltf.istream_ignore(self, *args)

    def peek(self):
        return _RWGltf.istream_peek(self)

    def read(self, __s, __n):
        return _RWGltf.istream_read(self, __s, __n)

    def readsome(self, __s, __n):
        return _RWGltf.istream_readsome(self, __s, __n)

    def putback(self, __c):
        return _RWGltf.istream_putback(self, __c)

    def unget(self):
        return _RWGltf.istream_unget(self)

    def sync(self):
        return _RWGltf.istream_sync(self)

    def tellg(self):
        return _RWGltf.istream_tellg(self)

    def seekg(self, *args):
        return _RWGltf.istream_seekg(self, *args)

# Register istream in _RWGltf:
_RWGltf.istream_swigregister(istream)
class iostream(istream, ostream):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, __sb):
        _RWGltf.iostream_swiginit(self, _RWGltf.new_iostream(__sb))
    __swig_destroy__ = _RWGltf.delete_iostream

# Register iostream in _RWGltf:
_RWGltf.iostream_swigregister(iostream)
cin = cvar.cin
cout = cvar.cout
cerr = cvar.cerr
clog = cvar.clog

endl_cb_ptr = _RWGltf.endl_cb_ptr
endl = _RWGltf.endl
ends_cb_ptr = _RWGltf.ends_cb_ptr
ends = _RWGltf.ends
flush_cb_ptr = _RWGltf.flush_cb_ptr
flush = _RWGltf.flush
import OCC.Core.Standard
import OCC.Core.NCollection
import OCC.Core.RWMesh
import OCC.Core.TDF
import OCC.Core.TCollection
import OCC.Core.TColStd
import OCC.Core.TDocStd
import OCC.Core.CDF
import OCC.Core.CDM
import OCC.Core.Message
import OCC.Core.OSD
import OCC.Core.Resource
import OCC.Core.PCDM
import OCC.Core.Storage
import OCC.Core.gp
import OCC.Core.TopoDS
import OCC.Core.TopAbs
import OCC.Core.TopLoc
import OCC.Core.Graphic3d
import OCC.Core.BVH
import OCC.Core.Quantity
import OCC.Core.Aspect
import OCC.Core.Image
import OCC.Core.Bnd
import OCC.Core.TColgp
import OCC.Core.Media
import OCC.Core.XCAFPrs
import OCC.Core.AIS
import OCC.Core.SelectMgr
import OCC.Core.Select3D
import OCC.Core.SelectBasics
import OCC.Core.Geom
import OCC.Core.GeomAbs
import OCC.Core.PrsMgr
import OCC.Core.Prs3d
import OCC.Core.Poly
import OCC.Core.TShort
import OCC.Core.V3d
import OCC.Core.StdSelect
import OCC.Core.TopTools
import OCC.Core.XCAFDoc
import OCC.Core.TDataStd
import OCC.Core.XCAFDimTolObjects
import OCC.Core.UnitsMethods
import OCC.Core.XCAFNoteObjects
import OCC.Core.XCAFView
import OCC.Core.TPrsStd
import OCC.Core.TDataXtd
import OCC.Core.TNaming

from enum import IntEnum
from OCC.Core.Exception import *

RWGltf_GltfAccessorCompType_UNKNOWN = _RWGltf.RWGltf_GltfAccessorCompType_UNKNOWN
RWGltf_GltfAccessorCompType_Int8 = _RWGltf.RWGltf_GltfAccessorCompType_Int8
RWGltf_GltfAccessorCompType_UInt8 = _RWGltf.RWGltf_GltfAccessorCompType_UInt8
RWGltf_GltfAccessorCompType_Int16 = _RWGltf.RWGltf_GltfAccessorCompType_Int16
RWGltf_GltfAccessorCompType_UInt16 = _RWGltf.RWGltf_GltfAccessorCompType_UInt16
RWGltf_GltfAccessorCompType_UInt32 = _RWGltf.RWGltf_GltfAccessorCompType_UInt32
RWGltf_GltfAccessorCompType_Float32 = _RWGltf.RWGltf_GltfAccessorCompType_Float32
RWGltf_GltfAccessorLayout_UNKNOWN = _RWGltf.RWGltf_GltfAccessorLayout_UNKNOWN
RWGltf_GltfAccessorLayout_Scalar = _RWGltf.RWGltf_GltfAccessorLayout_Scalar
RWGltf_GltfAccessorLayout_Vec2 = _RWGltf.RWGltf_GltfAccessorLayout_Vec2
RWGltf_GltfAccessorLayout_Vec3 = _RWGltf.RWGltf_GltfAccessorLayout_Vec3
RWGltf_GltfAccessorLayout_Vec4 = _RWGltf.RWGltf_GltfAccessorLayout_Vec4
RWGltf_GltfAccessorLayout_Mat2 = _RWGltf.RWGltf_GltfAccessorLayout_Mat2
RWGltf_GltfAccessorLayout_Mat3 = _RWGltf.RWGltf_GltfAccessorLayout_Mat3
RWGltf_GltfAccessorLayout_Mat4 = _RWGltf.RWGltf_GltfAccessorLayout_Mat4
RWGltf_GltfAlphaMode_Opaque = _RWGltf.RWGltf_GltfAlphaMode_Opaque
RWGltf_GltfAlphaMode_Mask = _RWGltf.RWGltf_GltfAlphaMode_Mask
RWGltf_GltfAlphaMode_Blend = _RWGltf.RWGltf_GltfAlphaMode_Blend
RWGltf_GltfArrayType_UNKNOWN = _RWGltf.RWGltf_GltfArrayType_UNKNOWN
RWGltf_GltfArrayType_Indices = _RWGltf.RWGltf_GltfArrayType_Indices
RWGltf_GltfArrayType_Position = _RWGltf.RWGltf_GltfArrayType_Position
RWGltf_GltfArrayType_Normal = _RWGltf.RWGltf_GltfArrayType_Normal
RWGltf_GltfArrayType_Color = _RWGltf.RWGltf_GltfArrayType_Color
RWGltf_GltfArrayType_TCoord0 = _RWGltf.RWGltf_GltfArrayType_TCoord0
RWGltf_GltfArrayType_TCoord1 = _RWGltf.RWGltf_GltfArrayType_TCoord1
RWGltf_GltfArrayType_Joint = _RWGltf.RWGltf_GltfArrayType_Joint
RWGltf_GltfArrayType_Weight = _RWGltf.RWGltf_GltfArrayType_Weight
RWGltf_GltfBufferViewTarget_UNKNOWN = _RWGltf.RWGltf_GltfBufferViewTarget_UNKNOWN
RWGltf_GltfBufferViewTarget_ARRAY_BUFFER = _RWGltf.RWGltf_GltfBufferViewTarget_ARRAY_BUFFER
RWGltf_GltfBufferViewTarget_ELEMENT_ARRAY_BUFFER = _RWGltf.RWGltf_GltfBufferViewTarget_ELEMENT_ARRAY_BUFFER
RWGltf_GltfPrimitiveMode_UNKNOWN = _RWGltf.RWGltf_GltfPrimitiveMode_UNKNOWN
RWGltf_GltfPrimitiveMode_Points = _RWGltf.RWGltf_GltfPrimitiveMode_Points
RWGltf_GltfPrimitiveMode_Lines = _RWGltf.RWGltf_GltfPrimitiveMode_Lines
RWGltf_GltfPrimitiveMode_LineLoop = _RWGltf.RWGltf_GltfPrimitiveMode_LineLoop
RWGltf_GltfPrimitiveMode_LineStrip = _RWGltf.RWGltf_GltfPrimitiveMode_LineStrip
RWGltf_GltfPrimitiveMode_Triangles = _RWGltf.RWGltf_GltfPrimitiveMode_Triangles
RWGltf_GltfPrimitiveMode_TriangleStrip = _RWGltf.RWGltf_GltfPrimitiveMode_TriangleStrip
RWGltf_GltfPrimitiveMode_TriangleFan = _RWGltf.RWGltf_GltfPrimitiveMode_TriangleFan
RWGltf_GltfRootElement_Asset = _RWGltf.RWGltf_GltfRootElement_Asset
RWGltf_GltfRootElement_Scenes = _RWGltf.RWGltf_GltfRootElement_Scenes
RWGltf_GltfRootElement_Scene = _RWGltf.RWGltf_GltfRootElement_Scene
RWGltf_GltfRootElement_Nodes = _RWGltf.RWGltf_GltfRootElement_Nodes
RWGltf_GltfRootElement_Meshes = _RWGltf.RWGltf_GltfRootElement_Meshes
RWGltf_GltfRootElement_Accessors = _RWGltf.RWGltf_GltfRootElement_Accessors
RWGltf_GltfRootElement_BufferViews = _RWGltf.RWGltf_GltfRootElement_BufferViews
RWGltf_GltfRootElement_Buffers = _RWGltf.RWGltf_GltfRootElement_Buffers
RWGltf_GltfRootElement_NB_MANDATORY = _RWGltf.RWGltf_GltfRootElement_NB_MANDATORY
RWGltf_GltfRootElement_Animations = _RWGltf.RWGltf_GltfRootElement_Animations
RWGltf_GltfRootElement_Materials = _RWGltf.RWGltf_GltfRootElement_Materials
RWGltf_GltfRootElement_Programs = _RWGltf.RWGltf_GltfRootElement_Programs
RWGltf_GltfRootElement_Samplers = _RWGltf.RWGltf_GltfRootElement_Samplers
RWGltf_GltfRootElement_Shaders = _RWGltf.RWGltf_GltfRootElement_Shaders
RWGltf_GltfRootElement_Skins = _RWGltf.RWGltf_GltfRootElement_Skins
RWGltf_GltfRootElement_Techniques = _RWGltf.RWGltf_GltfRootElement_Techniques
RWGltf_GltfRootElement_Textures = _RWGltf.RWGltf_GltfRootElement_Textures
RWGltf_GltfRootElement_Images = _RWGltf.RWGltf_GltfRootElement_Images
RWGltf_GltfRootElement_ExtensionsUsed = _RWGltf.RWGltf_GltfRootElement_ExtensionsUsed
RWGltf_GltfRootElement_ExtensionsRequired = _RWGltf.RWGltf_GltfRootElement_ExtensionsRequired
RWGltf_GltfRootElement_NB = _RWGltf.RWGltf_GltfRootElement_NB
RWGltf_WriterTrsfFormat_Compact = _RWGltf.RWGltf_WriterTrsfFormat_Compact
RWGltf_WriterTrsfFormat_Mat4 = _RWGltf.RWGltf_WriterTrsfFormat_Mat4
RWGltf_WriterTrsfFormat_TRS = _RWGltf.RWGltf_WriterTrsfFormat_TRS
RWGltf_WriterTrsfFormat_LOWER = _RWGltf.RWGltf_WriterTrsfFormat_LOWER
RWGltf_WriterTrsfFormat_UPPER = _RWGltf.RWGltf_WriterTrsfFormat_UPPER


class RWGltf_GltfAccessorCompType(IntEnum):
	RWGltf_GltfAccessorCompType_UNKNOWN = 0
	RWGltf_GltfAccessorCompType_Int8 = 5120
	RWGltf_GltfAccessorCompType_UInt8 = 5121
	RWGltf_GltfAccessorCompType_Int16 = 5122
	RWGltf_GltfAccessorCompType_UInt16 = 5123
	RWGltf_GltfAccessorCompType_UInt32 = 5125
	RWGltf_GltfAccessorCompType_Float32 = 5126
RWGltf_GltfAccessorCompType_UNKNOWN = RWGltf_GltfAccessorCompType.RWGltf_GltfAccessorCompType_UNKNOWN
RWGltf_GltfAccessorCompType_Int8 = RWGltf_GltfAccessorCompType.RWGltf_GltfAccessorCompType_Int8
RWGltf_GltfAccessorCompType_UInt8 = RWGltf_GltfAccessorCompType.RWGltf_GltfAccessorCompType_UInt8
RWGltf_GltfAccessorCompType_Int16 = RWGltf_GltfAccessorCompType.RWGltf_GltfAccessorCompType_Int16
RWGltf_GltfAccessorCompType_UInt16 = RWGltf_GltfAccessorCompType.RWGltf_GltfAccessorCompType_UInt16
RWGltf_GltfAccessorCompType_UInt32 = RWGltf_GltfAccessorCompType.RWGltf_GltfAccessorCompType_UInt32
RWGltf_GltfAccessorCompType_Float32 = RWGltf_GltfAccessorCompType.RWGltf_GltfAccessorCompType_Float32

class RWGltf_GltfAccessorLayout(IntEnum):
	RWGltf_GltfAccessorLayout_UNKNOWN = 0
	RWGltf_GltfAccessorLayout_Scalar = 1
	RWGltf_GltfAccessorLayout_Vec2 = 2
	RWGltf_GltfAccessorLayout_Vec3 = 3
	RWGltf_GltfAccessorLayout_Vec4 = 4
	RWGltf_GltfAccessorLayout_Mat2 = 5
	RWGltf_GltfAccessorLayout_Mat3 = 6
	RWGltf_GltfAccessorLayout_Mat4 = 7
RWGltf_GltfAccessorLayout_UNKNOWN = RWGltf_GltfAccessorLayout.RWGltf_GltfAccessorLayout_UNKNOWN
RWGltf_GltfAccessorLayout_Scalar = RWGltf_GltfAccessorLayout.RWGltf_GltfAccessorLayout_Scalar
RWGltf_GltfAccessorLayout_Vec2 = RWGltf_GltfAccessorLayout.RWGltf_GltfAccessorLayout_Vec2
RWGltf_GltfAccessorLayout_Vec3 = RWGltf_GltfAccessorLayout.RWGltf_GltfAccessorLayout_Vec3
RWGltf_GltfAccessorLayout_Vec4 = RWGltf_GltfAccessorLayout.RWGltf_GltfAccessorLayout_Vec4
RWGltf_GltfAccessorLayout_Mat2 = RWGltf_GltfAccessorLayout.RWGltf_GltfAccessorLayout_Mat2
RWGltf_GltfAccessorLayout_Mat3 = RWGltf_GltfAccessorLayout.RWGltf_GltfAccessorLayout_Mat3
RWGltf_GltfAccessorLayout_Mat4 = RWGltf_GltfAccessorLayout.RWGltf_GltfAccessorLayout_Mat4

class RWGltf_GltfAlphaMode(IntEnum):
	RWGltf_GltfAlphaMode_Opaque = 0
	RWGltf_GltfAlphaMode_Mask = 1
	RWGltf_GltfAlphaMode_Blend = 2
RWGltf_GltfAlphaMode_Opaque = RWGltf_GltfAlphaMode.RWGltf_GltfAlphaMode_Opaque
RWGltf_GltfAlphaMode_Mask = RWGltf_GltfAlphaMode.RWGltf_GltfAlphaMode_Mask
RWGltf_GltfAlphaMode_Blend = RWGltf_GltfAlphaMode.RWGltf_GltfAlphaMode_Blend

class RWGltf_GltfArrayType(IntEnum):
	RWGltf_GltfArrayType_UNKNOWN = 0
	RWGltf_GltfArrayType_Indices = 1
	RWGltf_GltfArrayType_Position = 2
	RWGltf_GltfArrayType_Normal = 3
	RWGltf_GltfArrayType_Color = 4
	RWGltf_GltfArrayType_TCoord0 = 5
	RWGltf_GltfArrayType_TCoord1 = 6
	RWGltf_GltfArrayType_Joint = 7
	RWGltf_GltfArrayType_Weight = 8
RWGltf_GltfArrayType_UNKNOWN = RWGltf_GltfArrayType.RWGltf_GltfArrayType_UNKNOWN
RWGltf_GltfArrayType_Indices = RWGltf_GltfArrayType.RWGltf_GltfArrayType_Indices
RWGltf_GltfArrayType_Position = RWGltf_GltfArrayType.RWGltf_GltfArrayType_Position
RWGltf_GltfArrayType_Normal = RWGltf_GltfArrayType.RWGltf_GltfArrayType_Normal
RWGltf_GltfArrayType_Color = RWGltf_GltfArrayType.RWGltf_GltfArrayType_Color
RWGltf_GltfArrayType_TCoord0 = RWGltf_GltfArrayType.RWGltf_GltfArrayType_TCoord0
RWGltf_GltfArrayType_TCoord1 = RWGltf_GltfArrayType.RWGltf_GltfArrayType_TCoord1
RWGltf_GltfArrayType_Joint = RWGltf_GltfArrayType.RWGltf_GltfArrayType_Joint
RWGltf_GltfArrayType_Weight = RWGltf_GltfArrayType.RWGltf_GltfArrayType_Weight

class RWGltf_GltfBufferViewTarget(IntEnum):
	RWGltf_GltfBufferViewTarget_UNKNOWN = 0
	RWGltf_GltfBufferViewTarget_ARRAY_BUFFER = 34962
	RWGltf_GltfBufferViewTarget_ELEMENT_ARRAY_BUFFER = 34963
RWGltf_GltfBufferViewTarget_UNKNOWN = RWGltf_GltfBufferViewTarget.RWGltf_GltfBufferViewTarget_UNKNOWN
RWGltf_GltfBufferViewTarget_ARRAY_BUFFER = RWGltf_GltfBufferViewTarget.RWGltf_GltfBufferViewTarget_ARRAY_BUFFER
RWGltf_GltfBufferViewTarget_ELEMENT_ARRAY_BUFFER = RWGltf_GltfBufferViewTarget.RWGltf_GltfBufferViewTarget_ELEMENT_ARRAY_BUFFER

class RWGltf_GltfPrimitiveMode(IntEnum):
	RWGltf_GltfPrimitiveMode_UNKNOWN = - 1
	RWGltf_GltfPrimitiveMode_Points = 0
	RWGltf_GltfPrimitiveMode_Lines = 1
	RWGltf_GltfPrimitiveMode_LineLoop = 2
	RWGltf_GltfPrimitiveMode_LineStrip = 3
	RWGltf_GltfPrimitiveMode_Triangles = 4
	RWGltf_GltfPrimitiveMode_TriangleStrip = 5
	RWGltf_GltfPrimitiveMode_TriangleFan = 6
RWGltf_GltfPrimitiveMode_UNKNOWN = RWGltf_GltfPrimitiveMode.RWGltf_GltfPrimitiveMode_UNKNOWN
RWGltf_GltfPrimitiveMode_Points = RWGltf_GltfPrimitiveMode.RWGltf_GltfPrimitiveMode_Points
RWGltf_GltfPrimitiveMode_Lines = RWGltf_GltfPrimitiveMode.RWGltf_GltfPrimitiveMode_Lines
RWGltf_GltfPrimitiveMode_LineLoop = RWGltf_GltfPrimitiveMode.RWGltf_GltfPrimitiveMode_LineLoop
RWGltf_GltfPrimitiveMode_LineStrip = RWGltf_GltfPrimitiveMode.RWGltf_GltfPrimitiveMode_LineStrip
RWGltf_GltfPrimitiveMode_Triangles = RWGltf_GltfPrimitiveMode.RWGltf_GltfPrimitiveMode_Triangles
RWGltf_GltfPrimitiveMode_TriangleStrip = RWGltf_GltfPrimitiveMode.RWGltf_GltfPrimitiveMode_TriangleStrip
RWGltf_GltfPrimitiveMode_TriangleFan = RWGltf_GltfPrimitiveMode.RWGltf_GltfPrimitiveMode_TriangleFan

class RWGltf_GltfRootElement(IntEnum):
	RWGltf_GltfRootElement_Asset = 0
	RWGltf_GltfRootElement_Scenes = 1
	RWGltf_GltfRootElement_Scene = 2
	RWGltf_GltfRootElement_Nodes = 3
	RWGltf_GltfRootElement_Meshes = 4
	RWGltf_GltfRootElement_Accessors = 5
	RWGltf_GltfRootElement_BufferViews = 6
	RWGltf_GltfRootElement_Buffers = 7
	RWGltf_GltfRootElement_NB_MANDATORY = 8
	RWGltf_GltfRootElement_Animations = RWGltf_GltfRootElement_NB_MANDATORY
	RWGltf_GltfRootElement_Materials = 10
	RWGltf_GltfRootElement_Programs = 11
	RWGltf_GltfRootElement_Samplers = 12
	RWGltf_GltfRootElement_Shaders = 13
	RWGltf_GltfRootElement_Skins = 14
	RWGltf_GltfRootElement_Techniques = 15
	RWGltf_GltfRootElement_Textures = 16
	RWGltf_GltfRootElement_Images = 17
	RWGltf_GltfRootElement_ExtensionsUsed = 18
	RWGltf_GltfRootElement_ExtensionsRequired = 19
	RWGltf_GltfRootElement_NB = 20
RWGltf_GltfRootElement_Asset = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Asset
RWGltf_GltfRootElement_Scenes = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Scenes
RWGltf_GltfRootElement_Scene = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Scene
RWGltf_GltfRootElement_Nodes = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Nodes
RWGltf_GltfRootElement_Meshes = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Meshes
RWGltf_GltfRootElement_Accessors = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Accessors
RWGltf_GltfRootElement_BufferViews = RWGltf_GltfRootElement.RWGltf_GltfRootElement_BufferViews
RWGltf_GltfRootElement_Buffers = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Buffers
RWGltf_GltfRootElement_NB_MANDATORY = RWGltf_GltfRootElement.RWGltf_GltfRootElement_NB_MANDATORY
RWGltf_GltfRootElement_Animations = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Animations
RWGltf_GltfRootElement_Materials = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Materials
RWGltf_GltfRootElement_Programs = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Programs
RWGltf_GltfRootElement_Samplers = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Samplers
RWGltf_GltfRootElement_Shaders = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Shaders
RWGltf_GltfRootElement_Skins = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Skins
RWGltf_GltfRootElement_Techniques = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Techniques
RWGltf_GltfRootElement_Textures = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Textures
RWGltf_GltfRootElement_Images = RWGltf_GltfRootElement.RWGltf_GltfRootElement_Images
RWGltf_GltfRootElement_ExtensionsUsed = RWGltf_GltfRootElement.RWGltf_GltfRootElement_ExtensionsUsed
RWGltf_GltfRootElement_ExtensionsRequired = RWGltf_GltfRootElement.RWGltf_GltfRootElement_ExtensionsRequired
RWGltf_GltfRootElement_NB = RWGltf_GltfRootElement.RWGltf_GltfRootElement_NB

class RWGltf_WriterTrsfFormat(IntEnum):
	RWGltf_WriterTrsfFormat_Compact = 0
	RWGltf_WriterTrsfFormat_Mat4 = 1
	RWGltf_WriterTrsfFormat_TRS = 2
RWGltf_WriterTrsfFormat_Compact = RWGltf_WriterTrsfFormat.RWGltf_WriterTrsfFormat_Compact
RWGltf_WriterTrsfFormat_Mat4 = RWGltf_WriterTrsfFormat.RWGltf_WriterTrsfFormat_Mat4
RWGltf_WriterTrsfFormat_TRS = RWGltf_WriterTrsfFormat.RWGltf_WriterTrsfFormat_TRS


def Handle_RWGltf_CafWriter_Create():
    return _RWGltf.Handle_RWGltf_CafWriter_Create()

def Handle_RWGltf_CafWriter_DownCast(t):
    return _RWGltf.Handle_RWGltf_CafWriter_DownCast(t)

def Handle_RWGltf_CafWriter_IsNull(t):
    return _RWGltf.Handle_RWGltf_CafWriter_IsNull(t)

def Handle_RWGltf_CafWriter_ForceRelease(t):
    return _RWGltf.Handle_RWGltf_CafWriter_ForceRelease(t)

def Handle_RWGltf_CafWriter_GetRefCount(t):
    return _RWGltf.Handle_RWGltf_CafWriter_GetRefCount(t)

def Handle_RWGltf_GltfFace_Create():
    return _RWGltf.Handle_RWGltf_GltfFace_Create()

def Handle_RWGltf_GltfFace_DownCast(t):
    return _RWGltf.Handle_RWGltf_GltfFace_DownCast(t)

def Handle_RWGltf_GltfFace_IsNull(t):
    return _RWGltf.Handle_RWGltf_GltfFace_IsNull(t)

def Handle_RWGltf_GltfFace_ForceRelease(t):
    return _RWGltf.Handle_RWGltf_GltfFace_ForceRelease(t)

def Handle_RWGltf_GltfFace_GetRefCount(t):
    return _RWGltf.Handle_RWGltf_GltfFace_GetRefCount(t)

def Handle_RWGltf_MaterialCommon_Create():
    return _RWGltf.Handle_RWGltf_MaterialCommon_Create()

def Handle_RWGltf_MaterialCommon_DownCast(t):
    return _RWGltf.Handle_RWGltf_MaterialCommon_DownCast(t)

def Handle_RWGltf_MaterialCommon_IsNull(t):
    return _RWGltf.Handle_RWGltf_MaterialCommon_IsNull(t)

def Handle_RWGltf_MaterialCommon_ForceRelease(t):
    return _RWGltf.Handle_RWGltf_MaterialCommon_ForceRelease(t)

def Handle_RWGltf_MaterialCommon_GetRefCount(t):
    return _RWGltf.Handle_RWGltf_MaterialCommon_GetRefCount(t)

def Handle_RWGltf_MaterialMetallicRoughness_Create():
    return _RWGltf.Handle_RWGltf_MaterialMetallicRoughness_Create()

def Handle_RWGltf_MaterialMetallicRoughness_DownCast(t):
    return _RWGltf.Handle_RWGltf_MaterialMetallicRoughness_DownCast(t)

def Handle_RWGltf_MaterialMetallicRoughness_IsNull(t):
    return _RWGltf.Handle_RWGltf_MaterialMetallicRoughness_IsNull(t)

def Handle_RWGltf_MaterialMetallicRoughness_ForceRelease(t):
    return _RWGltf.Handle_RWGltf_MaterialMetallicRoughness_ForceRelease(t)

def Handle_RWGltf_MaterialMetallicRoughness_GetRefCount(t):
    return _RWGltf.Handle_RWGltf_MaterialMetallicRoughness_GetRefCount(t)
class RWGltf_CafReader(OCC.Core.RWMesh.RWMesh_CafReader):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Empty constructor.

        """
        _RWGltf.RWGltf_CafReader_swiginit(self, _RWGltf.new_RWGltf_CafReader(*args))

    def IsDoublePrecision(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Return flag to fill in triangulation using double or single precision; False by default.

        """
        return _RWGltf.RWGltf_CafReader_IsDoublePrecision(self, *args)

    def SetDoublePrecision(self, *args):
        r"""

        Parameters
        ----------
        theIsDouble: bool

        Return
        -------
        None

        Description
        -----------
        Set flag to fill in triangulation using double or single precision.

        """
        return _RWGltf.RWGltf_CafReader_SetDoublePrecision(self, *args)

    def SetLoadAllScenes(self, *args):
        r"""

        Parameters
        ----------
        theToLoadAll: bool

        Return
        -------
        None

        Description
        -----------
        Set flag to flag to load all scenes in the document, False by default which means only main (default) scene will be loaded.

        """
        return _RWGltf.RWGltf_CafReader_SetLoadAllScenes(self, *args)

    def SetMeshNameAsFallback(self, *args):
        r"""

        Parameters
        ----------
        theToFallback: bool

        Return
        -------
        None

        Description
        -----------
        Set flag to use Mesh name in case if Node name is empty.

        """
        return _RWGltf.RWGltf_CafReader_SetMeshNameAsFallback(self, *args)

    def SetParallel(self, *args):
        r"""

        Parameters
        ----------
        theToParallel: bool

        Return
        -------
        None

        Description
        -----------
        Setup multithreaded execution.

        """
        return _RWGltf.RWGltf_CafReader_SetParallel(self, *args)

    def SetSkipEmptyNodes(self, *args):
        r"""

        Parameters
        ----------
        theToSkip: bool

        Return
        -------
        None

        Description
        -----------
        Set flag to ignore nodes without Geometry.

        """
        return _RWGltf.RWGltf_CafReader_SetSkipEmptyNodes(self, *args)

    def SetToKeepLateData(self, *args):
        r"""

        Parameters
        ----------
        theToKeep: bool

        Return
        -------
        None

        Description
        -----------
        Sets flag to keep information about deferred storage to load/unload data later.

        """
        return _RWGltf.RWGltf_CafReader_SetToKeepLateData(self, *args)

    def SetToPrintDebugMessages(self, *args):
        r"""

        Parameters
        ----------
        theToPrint: bool

        Return
        -------
        None

        Description
        -----------
        Sets flag to print debug information.

        """
        return _RWGltf.RWGltf_CafReader_SetToPrintDebugMessages(self, *args)

    def SetToSkipLateDataLoading(self, *args):
        r"""

        Parameters
        ----------
        theToSkip: bool

        Return
        -------
        None

        Description
        -----------
        Sets flag to skip data loading.

        """
        return _RWGltf.RWGltf_CafReader_SetToSkipLateDataLoading(self, *args)

    def ToKeepLateData(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Returns True if data should be loaded into itself without its transferring to new structure. It allows to keep information about deferred storage to load/unload this data later. True by default.

        """
        return _RWGltf.RWGltf_CafReader_ToKeepLateData(self, *args)

    def ToLoadAllScenes(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Return True if all scenes in the document should be loaded, False by default which means only main (default) scene will be loaded.

        """
        return _RWGltf.RWGltf_CafReader_ToLoadAllScenes(self, *args)

    def ToParallel(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Return True if multithreaded optimizations are allowed; False by default.

        """
        return _RWGltf.RWGltf_CafReader_ToParallel(self, *args)

    def ToPrintDebugMessages(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Returns True if additional debug information should be print; False by default.

        """
        return _RWGltf.RWGltf_CafReader_ToPrintDebugMessages(self, *args)

    def ToSkipEmptyNodes(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Return True if Nodes without Geometry should be ignored, True by default.

        """
        return _RWGltf.RWGltf_CafReader_ToSkipEmptyNodes(self, *args)

    def ToSkipLateDataLoading(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Returns True if data loading should be skipped and can be performed later; False by default.

        """
        return _RWGltf.RWGltf_CafReader_ToSkipLateDataLoading(self, *args)

    def ToUseMeshNameAsFallback(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Set flag to use Mesh name in case if Node name is empty, True by default.

        """
        return _RWGltf.RWGltf_CafReader_ToUseMeshNameAsFallback(self, *args)

    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_CafReader

# Register RWGltf_CafReader in _RWGltf:
_RWGltf.RWGltf_CafReader_swigregister(RWGltf_CafReader)
class RWGltf_CafWriter(OCC.Core.Standard.Standard_Transient):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""

        Parameters
        ----------
        theFile: str
        theIsBinary: bool

        Return
        -------
        None

        Description
        -----------
        Main constructor. 
        Input parameter: theFile path to output glTF file 
        Input parameter: theIsBinary flag to write into binary glTF format (.glb).

        """
        _RWGltf.RWGltf_CafWriter_swiginit(self, _RWGltf.new_RWGltf_CafWriter(*args))

    def ChangeCoordinateSystemConverter(self, *args):
        r"""
        Return
        -------
        RWMesh_CoordinateSystemConverter

        Description
        -----------
        Return transformation from OCCT to glTF coordinate system.

        """
        return _RWGltf.RWGltf_CafWriter_ChangeCoordinateSystemConverter(self, *args)

    def CompressionParameters(self, *args):
        r"""
        Return
        -------
        RWGltf_DracoParameters

        Description
        -----------
        Return Draco parameters.

        """
        return _RWGltf.RWGltf_CafWriter_CompressionParameters(self, *args)

    def CoordinateSystemConverter(self, *args):
        r"""
        Return
        -------
        RWMesh_CoordinateSystemConverter

        Description
        -----------
        Return transformation from OCCT to glTF coordinate system.

        """
        return _RWGltf.RWGltf_CafWriter_CoordinateSystemConverter(self, *args)

    def DefaultStyle(self, *args):
        r"""
        Return
        -------
        XCAFPrs_Style

        Description
        -----------
        Return default material definition to be used for nodes with only color defined.

        """
        return _RWGltf.RWGltf_CafWriter_DefaultStyle(self, *args)

    def IsBinary(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Return flag to write into binary glTF format (.glb), specified within class constructor.

        """
        return _RWGltf.RWGltf_CafWriter_IsBinary(self, *args)

    def IsForcedUVExport(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Return True to export UV coordinates even if there are no mapped texture; False by default.

        """
        return _RWGltf.RWGltf_CafWriter_IsForcedUVExport(self, *args)

    def MeshNameFormat(self, *args):
        r"""
        Return
        -------
        RWMesh_NameFormat

        Description
        -----------
        Return name format for exporting Meshes; RWMesh_NameFormat_Product by default.

        """
        return _RWGltf.RWGltf_CafWriter_MeshNameFormat(self, *args)

    def NodeNameFormat(self, *args):
        r"""
        Return
        -------
        RWMesh_NameFormat

        Description
        -----------
        Return name format for exporting Nodes; RWMesh_NameFormat_InstanceOrProduct by default.

        """
        return _RWGltf.RWGltf_CafWriter_NodeNameFormat(self, *args)

    def Perform(self, *args):
        r"""

        Parameters
        ----------
        theDocument: TDocStd_Document
        theRootLabels: TDF_LabelSequence
        theLabelFilter: TColStd_MapOfAsciiString *
        theFileInfo: TColStd_IndexedDataMapOfStringString
        theProgress: Message_ProgressRange

        Return
        -------
        bool

        Description
        -----------
        Write glTF file and associated binary file. Triangulation data should be precomputed within shapes! 
        Input parameter: theDocument input document 
        Input parameter: theRootLabels list of root shapes to export 
        Input parameter: theLabelFilter optional filter with document nodes to export,  with keys defined by XCAFPrs_DocumentExplorer::DefineChildId() and  filled recursively (leaves and parent assembly nodes at all  levels); when not NULL, all nodes not included into the map will be  ignored 
        Input parameter: theFileInfo map with file metadata to put into glTF header section 
        Input parameter: theProgress optional progress indicator 
        Return: False on file writing failure.

        Parameters
        ----------
        theDocument: TDocStd_Document
        theFileInfo: TColStd_IndexedDataMapOfStringString
        theProgress: Message_ProgressRange

        Return
        -------
        bool

        Description
        -----------
        Write glTF file and associated binary file. Triangulation data should be precomputed within shapes! 
        Input parameter: theDocument input document 
        Input parameter: theFileInfo map with file metadata to put into glTF header section 
        Input parameter: theProgress optional progress indicator 
        Return: False on file writing failure.

        """
        return _RWGltf.RWGltf_CafWriter_Perform(self, *args)

    def SetCompressionParameters(self, *args):
        r"""

        Parameters
        ----------
        theDracoParameters: RWGltf_DracoParameters

        Return
        -------
        None

        Description
        -----------
        Set Draco parameters.

        """
        return _RWGltf.RWGltf_CafWriter_SetCompressionParameters(self, *args)

    def SetCoordinateSystemConverter(self, *args):
        r"""

        Parameters
        ----------
        theConverter: RWMesh_CoordinateSystemConverter

        Return
        -------
        None

        Description
        -----------
        Set transformation from OCCT to glTF coordinate system.

        """
        return _RWGltf.RWGltf_CafWriter_SetCoordinateSystemConverter(self, *args)

    def SetDefaultStyle(self, *args):
        r"""

        Parameters
        ----------
        theStyle: XCAFPrs_Style

        Return
        -------
        None

        Description
        -----------
        Set default material definition to be used for nodes with only color defined.

        """
        return _RWGltf.RWGltf_CafWriter_SetDefaultStyle(self, *args)

    def SetForcedUVExport(self, *args):
        r"""

        Parameters
        ----------
        theToForce: bool

        Return
        -------
        None

        Description
        -----------
        Set flag to export UV coordinates even if there are no mapped texture; False by default.

        """
        return _RWGltf.RWGltf_CafWriter_SetForcedUVExport(self, *args)

    def SetMergeFaces(self, *args):
        r"""

        Parameters
        ----------
        theToMerge: bool

        Return
        -------
        None

        Description
        -----------
        Set flag to merge faces within a single part. May reduce JSON size thanks to smaller number of primitive arrays.

        """
        return _RWGltf.RWGltf_CafWriter_SetMergeFaces(self, *args)

    def SetMeshNameFormat(self, *args):
        r"""

        Parameters
        ----------
        theFormat: RWMesh_NameFormat

        Return
        -------
        None

        Description
        -----------
        Set name format for exporting Meshes.

        """
        return _RWGltf.RWGltf_CafWriter_SetMeshNameFormat(self, *args)

    def SetNodeNameFormat(self, *args):
        r"""

        Parameters
        ----------
        theFormat: RWMesh_NameFormat

        Return
        -------
        None

        Description
        -----------
        Set name format for exporting Nodes.

        """
        return _RWGltf.RWGltf_CafWriter_SetNodeNameFormat(self, *args)

    def SetParallel(self, *args):
        r"""

        Parameters
        ----------
        theToParallel: bool

        Return
        -------
        None

        Description
        -----------
        Setup multithreaded execution.

        """
        return _RWGltf.RWGltf_CafWriter_SetParallel(self, *args)

    def SetSplitIndices16(self, *args):
        r"""

        Parameters
        ----------
        theToSplit: bool

        Return
        -------
        None

        Description
        -----------
        Set flag to prefer keeping 16-bit indexes while merging face. Has effect only with ToMergeFaces() option turned ON. May reduce binary data size thanks to smaller triangle indexes.

        """
        return _RWGltf.RWGltf_CafWriter_SetSplitIndices16(self, *args)

    def SetToEmbedTexturesInGlb(self, *args):
        r"""

        Parameters
        ----------
        theToEmbedTexturesInGlb: bool

        Return
        -------
        None

        Description
        -----------
        Set flag to write image textures into GLB file (binary gltf export).

        """
        return _RWGltf.RWGltf_CafWriter_SetToEmbedTexturesInGlb(self, *args)

    def SetTransformationFormat(self, *args):
        r"""

        Parameters
        ----------
        theFormat: RWGltf_WriterTrsfFormat

        Return
        -------
        None

        Description
        -----------
        Set preferred transformation format for writing into glTF file.

        """
        return _RWGltf.RWGltf_CafWriter_SetTransformationFormat(self, *args)

    def ToEmbedTexturesInGlb(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Return flag to write image textures into GLB file (binary gltf export); True by default. When set to False, texture images will be written as separate files. Has no effect on writing into non-binary format.

        """
        return _RWGltf.RWGltf_CafWriter_ToEmbedTexturesInGlb(self, *args)

    def ToMergeFaces(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Return flag to merge faces within a single part; False by default.

        """
        return _RWGltf.RWGltf_CafWriter_ToMergeFaces(self, *args)

    def ToParallel(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Return True if multithreaded optimizations are allowed; False by default.

        """
        return _RWGltf.RWGltf_CafWriter_ToParallel(self, *args)

    def ToSplitIndices16(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Return flag to prefer keeping 16-bit indexes while merging face; False by default.

        """
        return _RWGltf.RWGltf_CafWriter_ToSplitIndices16(self, *args)

    def TransformationFormat(self, *args):
        r"""
        Return
        -------
        RWGltf_WriterTrsfFormat

        Description
        -----------
        Return preferred transformation format for writing into glTF file; RWGltf_WriterTrsfFormat_Compact by default.

        """
        return _RWGltf.RWGltf_CafWriter_TransformationFormat(self, *args)


    @staticmethod
    def DownCast(t):
      return Handle_RWGltf_CafWriter_DownCast(t)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_CafWriter

# Register RWGltf_CafWriter in _RWGltf:
_RWGltf.RWGltf_CafWriter_swigregister(RWGltf_CafWriter)
class RWGltf_DracoParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        No available documentation.

        """
        _RWGltf.RWGltf_DracoParameters_swiginit(self, _RWGltf.new_RWGltf_DracoParameters(*args))

    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_DracoParameters

# Register RWGltf_DracoParameters in _RWGltf:
_RWGltf.RWGltf_DracoParameters_swigregister(RWGltf_DracoParameters)
class RWGltf_GltfAccessor(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Empty constructor.

        """
        _RWGltf.RWGltf_GltfAccessor_swiginit(self, _RWGltf.new_RWGltf_GltfAccessor(*args))

    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_GltfAccessor

# Register RWGltf_GltfAccessor in _RWGltf:
_RWGltf.RWGltf_GltfAccessor_swigregister(RWGltf_GltfAccessor)
class RWGltf_GltfBufferView(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        No available documentation.

        """
        _RWGltf.RWGltf_GltfBufferView_swiginit(self, _RWGltf.new_RWGltf_GltfBufferView(*args))

    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_GltfBufferView

# Register RWGltf_GltfBufferView in _RWGltf:
_RWGltf.RWGltf_GltfBufferView_swigregister(RWGltf_GltfBufferView)
class RWGltf_GltfFace(OCC.Core.Standard.Standard_Transient):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        No available documentation.

        """
        _RWGltf.RWGltf_GltfFace_swiginit(self, _RWGltf.new_RWGltf_GltfFace(*args))


    @staticmethod
    def DownCast(t):
      return Handle_RWGltf_GltfFace_DownCast(t)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_GltfFace

# Register RWGltf_GltfFace in _RWGltf:
_RWGltf.RWGltf_GltfFace_swigregister(RWGltf_GltfFace)
class RWGltf_GltfLatePrimitiveArray(OCC.Core.RWMesh.RWMesh_TriangulationSource):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""

        Parameters
        ----------
        theId: str
        theName: str

        Return
        -------
        None

        Description
        -----------
        Constructor.

        """
        _RWGltf.RWGltf_GltfLatePrimitiveArray_swiginit(self, _RWGltf.new_RWGltf_GltfLatePrimitiveArray(*args))

    def AddPrimArrayData(self, *args):
        r"""

        Parameters
        ----------
        theType: RWGltf_GltfArrayType

        Return
        -------
        RWGltf_GltfPrimArrayData

        Description
        -----------
        Add primitive array data element.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_AddPrimArrayData(self, *args)

    def BaseColor(self, *args):
        r"""
        Return
        -------
        Quantity_ColorRGBA

        Description
        -----------
        Return base color.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_BaseColor(self, *args)

    def Data(self, *args):
        r"""
        Return
        -------
        NCollection_Sequence<RWGltf_GltfPrimArrayData>

        Description
        -----------
        Return primitive array data elements.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_Data(self, *args)

    def HasStyle(self, *args):
        r"""
        Return
        -------
        bool

        Description
        -----------
        Return true if primitive array has assigned material.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_HasStyle(self, *args)

    def Id(self, *args):
        r"""
        Return
        -------
        TCollection_AsciiString

        Description
        -----------
        Entity id.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_Id(self, *args)

    def LoadStreamData(self, *args):
        r"""
        Return
        -------
        opencascade::handle<Poly_Triangulation>

        Description
        -----------
        Load primitive array saved as stream buffer to new triangulation object.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_LoadStreamData(self, *args)

    def MaterialCommon(self, *args):
        r"""
        Return
        -------
        opencascade::handle<RWGltf_MaterialCommon>

        Description
        -----------
        Return common (obsolete) material definition.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_MaterialCommon(self, *args)

    def MaterialPbr(self, *args):
        r"""
        Return
        -------
        opencascade::handle<RWGltf_MaterialMetallicRoughness>

        Description
        -----------
        Return PBR material definition.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_MaterialPbr(self, *args)

    def Name(self, *args):
        r"""
        Return
        -------
        TCollection_AsciiString

        Description
        -----------
        Entity name.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_Name(self, *args)

    def PrimitiveMode(self, *args):
        r"""
        Return
        -------
        RWGltf_GltfPrimitiveMode

        Description
        -----------
        Return type of primitive array.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_PrimitiveMode(self, *args)

    def SetMaterialCommon(self, *args):
        r"""

        Parameters
        ----------
        theMat: RWGltf_MaterialCommon

        Return
        -------
        None

        Description
        -----------
        Set common (obsolete) material definition.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_SetMaterialCommon(self, *args)

    def SetMaterialPbr(self, *args):
        r"""

        Parameters
        ----------
        theMat: RWGltf_MaterialMetallicRoughness

        Return
        -------
        None

        Description
        -----------
        Set PBR material definition.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_SetMaterialPbr(self, *args)

    def SetName(self, *args):
        r"""

        Parameters
        ----------
        theName: str

        Return
        -------
        None

        Description
        -----------
        Assign entity name.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_SetName(self, *args)

    def SetPrimitiveMode(self, *args):
        r"""

        Parameters
        ----------
        theMode: RWGltf_GltfPrimitiveMode

        Return
        -------
        None

        Description
        -----------
        Set type of primitive array.

        """
        return _RWGltf.RWGltf_GltfLatePrimitiveArray_SetPrimitiveMode(self, *args)

    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_GltfLatePrimitiveArray

# Register RWGltf_GltfLatePrimitiveArray in _RWGltf:
_RWGltf.RWGltf_GltfLatePrimitiveArray_swigregister(RWGltf_GltfLatePrimitiveArray)
class RWGltf_GltfMaterialMap(OCC.Core.RWMesh.RWMesh_MaterialMap):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""

        Parameters
        ----------
        theFile: str
        theDefSamplerId: int

        Return
        -------
        None

        Description
        -----------
        Main constructor.

        """
        _RWGltf.RWGltf_GltfMaterialMap_swiginit(self, _RWGltf.new_RWGltf_GltfMaterialMap(*args))

    def AddGlbImages(self, *args):
        r"""

        Parameters
        ----------
        theStyle: XCAFPrs_Style

        Return
        -------
        theBinFile: std::ostream

        Description
        -----------
        Add material images into GLB stream. 
        Input parameter:[out] theBinFile output file stream 
        Input parameter: theStyle material images to add.

        """
        return _RWGltf.RWGltf_GltfMaterialMap_AddGlbImages(self, *args)

    def AddImages(self, *args):
        r"""

        Parameters
        ----------
        theWriter: RWGltf_GltfOStreamWriter *
        theStyle: XCAFPrs_Style

        Return
        -------
        theIsStarted: bool

        Description
        -----------
        Add material images in case of non-GLB file (an alternative to AddImagesToGlb() + FlushBufferViews() + FlushImagesGlb()).

        """
        return _RWGltf.RWGltf_GltfMaterialMap_AddImages(self, *args)

    def AddMaterial(self, *args):
        r"""

        Parameters
        ----------
        theWriter: RWGltf_GltfOStreamWriter *
        theStyle: XCAFPrs_Style

        Return
        -------
        theIsStarted: bool

        Description
        -----------
        Add material.

        """
        return _RWGltf.RWGltf_GltfMaterialMap_AddMaterial(self, *args)

    def AddTextures(self, *args):
        r"""

        Parameters
        ----------
        theWriter: RWGltf_GltfOStreamWriter *
        theStyle: XCAFPrs_Style

        Return
        -------
        theIsStarted: bool

        Description
        -----------
        Add material textures.

        """
        return _RWGltf.RWGltf_GltfMaterialMap_AddTextures(self, *args)

    def FlushGlbBufferViews(self, *args):
        r"""

        Parameters
        ----------
        theWriter: RWGltf_GltfOStreamWriter *
        theBinDataBufferId: int

        Return
        -------
        theBuffViewId: int

        Description
        -----------
        Add bufferView's into RWGltf_GltfRootElement_BufferViews section with images collected by AddImagesToGlb().

        """
        return _RWGltf.RWGltf_GltfMaterialMap_FlushGlbBufferViews(self, *args)

    def FlushGlbImages(self, *args):
        r"""

        Parameters
        ----------
        theWriter: RWGltf_GltfOStreamWriter *

        Return
        -------
        None

        Description
        -----------
        Write RWGltf_GltfRootElement_Images section with images collected by AddImagesToGlb().

        """
        return _RWGltf.RWGltf_GltfMaterialMap_FlushGlbImages(self, *args)

    def NbImages(self, *args):
        r"""
        Return
        -------
        int

        Description
        -----------
        Return extent of images map.

        """
        return _RWGltf.RWGltf_GltfMaterialMap_NbImages(self, *args)

    def NbTextures(self, *args):
        r"""
        Return
        -------
        int

        Description
        -----------
        Return extent of textures map.

        """
        return _RWGltf.RWGltf_GltfMaterialMap_NbTextures(self, *args)

    @staticmethod
    def baseColorTexture(*args):
        r"""

        Parameters
        ----------
        theMat: XCAFDoc_VisMaterial

        Return
        -------
        opencascade::handle<Image_Texture>

        Description
        -----------
        Return base color texture.

        """
        return _RWGltf.RWGltf_GltfMaterialMap_baseColorTexture(*args)

    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_GltfMaterialMap

# Register RWGltf_GltfMaterialMap in _RWGltf:
_RWGltf.RWGltf_GltfMaterialMap_swigregister(RWGltf_GltfMaterialMap)
class RWGltf_GltfOStreamWriter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""

        Parameters
        ----------
        theOStream: rapidjson::OStreamWrapper

        Return
        -------
        None

        Description
        -----------
        Main constructor.

        """
        _RWGltf.RWGltf_GltfOStreamWriter_swiginit(self, _RWGltf.new_RWGltf_GltfOStreamWriter(*args))

    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_GltfOStreamWriter

# Register RWGltf_GltfOStreamWriter in _RWGltf:
_RWGltf.RWGltf_GltfOStreamWriter_swigregister(RWGltf_GltfOStreamWriter)
class RWGltf_GltfPrimArrayData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        No available documentation.

        Parameters
        ----------
        theType: RWGltf_GltfArrayType

        Return
        -------
        None

        Description
        -----------
        No available documentation.

        """
        _RWGltf.RWGltf_GltfPrimArrayData_swiginit(self, _RWGltf.new_RWGltf_GltfPrimArrayData(*args))

    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_GltfPrimArrayData

# Register RWGltf_GltfPrimArrayData in _RWGltf:
_RWGltf.RWGltf_GltfPrimArrayData_swigregister(RWGltf_GltfPrimArrayData)
class RWGltf_GltfSceneNodeMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Empty constructor.

        """
        _RWGltf.RWGltf_GltfSceneNodeMap_swiginit(self, _RWGltf.new_RWGltf_GltfSceneNodeMap(*args))

    def FindIndex(self, *args):
        r"""

        Parameters
        ----------
        theNodeId: str

        Return
        -------
        int

        Description
        -----------
        Find index from document node string identifier.

        """
        return _RWGltf.RWGltf_GltfSceneNodeMap_FindIndex(self, *args)

    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_GltfSceneNodeMap

# Register RWGltf_GltfSceneNodeMap in _RWGltf:
_RWGltf.RWGltf_GltfSceneNodeMap_swigregister(RWGltf_GltfSceneNodeMap)
class RWGltf_MaterialCommon(OCC.Core.Standard.Standard_Transient):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        No available documentation.

        """
        _RWGltf.RWGltf_MaterialCommon_swiginit(self, _RWGltf.new_RWGltf_MaterialCommon(*args))


    @staticmethod
    def DownCast(t):
      return Handle_RWGltf_MaterialCommon_DownCast(t)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_MaterialCommon

# Register RWGltf_MaterialCommon in _RWGltf:
_RWGltf.RWGltf_MaterialCommon_swigregister(RWGltf_MaterialCommon)
class RWGltf_MaterialMetallicRoughness(OCC.Core.Standard.Standard_Transient):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        No available documentation.

        """
        _RWGltf.RWGltf_MaterialMetallicRoughness_swiginit(self, _RWGltf.new_RWGltf_MaterialMetallicRoughness(*args))


    @staticmethod
    def DownCast(t):
      return Handle_RWGltf_MaterialMetallicRoughness_DownCast(t)


    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_MaterialMetallicRoughness

# Register RWGltf_MaterialMetallicRoughness in _RWGltf:
_RWGltf.RWGltf_MaterialMetallicRoughness_swigregister(RWGltf_MaterialMetallicRoughness)
class RWGltf_TriangulationReader(OCC.Core.RWMesh.RWMesh_TriangulationReader):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        Return
        -------
        None

        Description
        -----------
        Empty constructor.

        """
        _RWGltf.RWGltf_TriangulationReader_swiginit(self, _RWGltf.new_RWGltf_TriangulationReader(*args))

    def LoadStreamData(self, *args):
        r"""

        Parameters
        ----------
        theSourceMesh: RWMesh_TriangulationSource
        theDestMesh: Poly_Triangulation

        Return
        -------
        bool

        Description
        -----------
        Loads only primitive arrays saved as stream buffer (it is primarily glTF data encoded in base64 saved to temporary buffer during glTF file reading).

        """
        return _RWGltf.RWGltf_TriangulationReader_LoadStreamData(self, *args)

    __repr__ = _dumps_object

    __swig_destroy__ = _RWGltf.delete_RWGltf_TriangulationReader

# Register RWGltf_TriangulationReader in _RWGltf:
_RWGltf.RWGltf_TriangulationReader_swigregister(RWGltf_TriangulationReader)

@classnotwrapped
class RWGltf_GltfSharedIStream:
	pass





@deprecated
def RWGltf_GltfMaterialMap_baseColorTexture(*args):
	return RWGltf_GltfMaterialMap.baseColorTexture(*args)



